/// PADMÉ padding, mirroring `backend/crates/crypto/src/padding.rs`.
///
/// Padding hides the true length of a message from anyone observing the ciphertext. It is
/// applied to the plaintext *before* the AEAD, so the length that leaks is the padded one.
///
/// **This is not textbook PADMÉ, and the deviation is deliberate on the Rust side.** Below
/// 256 bytes it is 16-byte alignment with a 32-byte floor; only above that does the
/// exponential bucket formula apply. This file mirrors that exactly - matching the paper
/// rather than the implementation would produce lengths the other end does not expect, and
/// the padded plaintext would fail to unpad.
///
/// The scheme is verified against vectors generated by the Rust implementation in
/// `test/core/crypto/padme_test.dart`.
library;

import 'dart:typed_data';

import 'crypto_exceptions.dart';

/// Minimum padded length; prevents fingerprinting of very short messages.
const int padmeMinLength = 32;

/// Largest message the scheme will pad.
const int padmeMaxMessageLength = 16 * 1024 * 1024;

/// The padded length a message of [len] bytes will occupy.
///
/// Mirrors `next_padme_length`. Uses integer arithmetic throughout: the Rust version reaches
/// for `f64::log2`, and floating point has no place in deciding a buffer length that both
/// ends must agree on to the byte.
int nextPadmeLength(int len) {
  final effective = len < 1 ? 1 : len;
  final needed = effective + 1; // +1 for the 0x80 marker

  if (needed <= padmeMinLength) return padmeMinLength;

  if (needed <= 256) {
    // 16-byte alignment for small messages.
    return ((needed + 15) ~/ 16) * 16;
  }

  final e = needed.bitLength - 1; // floor(log2(needed))
  final s = (e.bitLength - 1) + 1; // floor(log2(e)) + 1

  if (e <= s) {
    // Edge case: round up to the next power of two.
    var p = 1;
    while (p < needed) {
      p <<= 1;
    }
    return p;
  }

  final granularity = 1 << (e - s);
  final padded = ((needed + granularity - 1) ~/ granularity) * granularity;
  return padded < needed ? needed : padded;
}

/// Pad [plaintext] to its PADMÉ length using ISO/IEC 7816-4 padding.
///
/// The marker is a single `0x80` immediately after the plaintext, followed by zeros.
Uint8List padMessage(Uint8List plaintext) {
  if (plaintext.length > padmeMaxMessageLength) {
    throw PaddingException(
      'Message too large: ${plaintext.length} bytes '
      '(max: $padmeMaxMessageLength)',
    );
  }

  final padded = Uint8List(nextPadmeLength(plaintext.length));
  padded.setRange(0, plaintext.length, plaintext);
  padded[plaintext.length] = 0x80;
  return padded;
}

/// Strip PADMÉ padding, returning the original plaintext.
///
/// Scans backwards for the `0x80` marker, rejecting any non-zero byte encountered first.
Uint8List unpadMessage(Uint8List padded) {
  if (padded.isEmpty) {
    throw PaddingException('Padded message too short');
  }

  for (var i = padded.length - 1; i >= 0; i--) {
    if (padded[i] == 0x80) {
      return Uint8List.fromList(padded.sublist(0, i));
    }
    if (padded[i] != 0x00) {
      throw PaddingException('Invalid padding bytes found');
    }
  }

  throw PaddingException('Padding marker not found');
}
