/// PADMÉ tests, pinned to vectors generated by the Rust implementation.
///
/// The lengths below came from `next_padme_length` in
/// `backend/crates/crypto/src/padding.rs`, not from reading the formula. Both ends must agree
/// on the padded length to the byte, or the receiver's unpad sees a buffer of the wrong size.
///
/// Note this is deliberately NOT textbook PADMÉ: below 256 bytes it is 16-byte alignment with
/// a 32-byte floor, and only above that does the exponential bucket apply. The vectors encode
/// that, which is the point - a "more correct" implementation would be wrong here.
library;

import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:guardyn_client/core/crypto/crypto_exceptions.dart';
import 'package:guardyn_client/core/crypto/padme.dart';

void main() {
  group('nextPadmeLength matches the Rust vectors', () {
    // length -> padded length, emitted by the Rust implementation.
    const vectors = <int, int>{
      0: 32,
      1: 32,
      2: 32,
      15: 32,
      30: 32,
      31: 32,
      32: 48,
      33: 48,
      47: 48,
      100: 112,
      200: 208,
      239: 240,
      240: 256,
      254: 256,
      255: 256,
      256: 272,
      257: 272,
      300: 304,
      511: 512,
      512: 544,
      1000: 1024,
      1024: 1088,
      4095: 4096,
      65535: 65536,
      100000: 100352,
      1048576: 1081344,
    };

    vectors.forEach((len, expected) {
      test('$len -> $expected', () {
        expect(nextPadmeLength(len), equals(expected));
      });
    });
  });

  group('padMessage / unpadMessage', () {
    test('produces the exact blob Rust produces for "hi"', () {
      final padded = padMessage(Uint8List.fromList(utf8.encode('hi')));
      expect(
        padded.map((b) => b.toRadixString(16).padLeft(2, '0')).join(),
        equals(
          '6869800000000000000000000000000000000000000000000000000000000000',
        ),
      );
    });

    test('round-trips across the vector set', () {
      for (final len in [0, 1, 31, 32, 33, 255, 256, 257, 1000, 4095, 65535]) {
        final msg = Uint8List.fromList(List.filled(len, 0x41));
        final padded = padMessage(msg);
        expect(padded.length, equals(nextPadmeLength(len)));
        expect(unpadMessage(padded), equals(msg));
      }
    });

    test('round-trips a message ending in zero bytes', () {
      // The marker scan walks back over zeros, so a plaintext that itself ends in 0x00 is the
      // case a naive implementation gets wrong.
      final msg = Uint8List.fromList([1, 2, 3, 0, 0, 0]);
      expect(unpadMessage(padMessage(msg)), equals(msg));
    });

    test('every padded length is at least the 32-byte floor', () {
      for (var len = 0; len < 64; len++) {
        expect(padMessage(Uint8List(len)).length, greaterThanOrEqualTo(32));
      }
    });

    test('rejects an empty buffer', () {
      expect(
        () => unpadMessage(Uint8List(0)),
        throwsA(isA<PaddingException>()),
      );
    });

    test('rejects a buffer with no marker', () {
      expect(
        () => unpadMessage(Uint8List(32)),
        throwsA(isA<PaddingException>()),
      );
    });

    test('rejects trailing garbage after the marker', () {
      final bad = Uint8List(32);
      bad[0] = 0x80;
      bad[31] = 0x7f; // non-zero, not the marker
      expect(() => unpadMessage(bad), throwsA(isA<PaddingException>()));
    });

    test('rejects a message larger than the maximum', () {
      expect(
        () => padMessage(Uint8List(padmeMaxMessageLength + 1)),
        throwsA(isA<PaddingException>()),
      );
    });
  });
}
