// Known-answer tests for the ratchet wire format.
//
// The vectors below were produced by the Rust implementation itself
// (backend/crates/crypto/src/double_ratchet.rs, EncryptedMessage::to_bytes), not derived by
// reading it. They exist because every other test in this suite is Dart-against-Dart: a
// round-trip passes just as happily when both sides share a bug, which is exactly how this
// client stayed on the pre-v1 format while the server moved off it.
//
// Format, per docs/adr/ADR-0011-ratchet-header-authentication.md:
//
//   version(1) || header_len:u32 BE(4) || header(40) || ciphertext
//   header = dh_public_key[32] || previous_chain_length:u32 BE || message_number:u32 BE
//
// If one of these fails, Dart and Rust disagree on the wire and messages will not cross
// between clients. Do not "fix" it by editing the vector.

import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:guardyn_client/core/crypto/crypto_exceptions.dart';
import 'package:guardyn_client/core/crypto/double_ratchet.dart';

Uint8List _hex(String h) {
  final out = Uint8List(h.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(h.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}

String _hexOf(Uint8List b) =>
    b.map((x) => x.toRadixString(16).padLeft(2, '0')).join();

void main() {
  // 0x00,0x01,...,0x1f - the DH public key used for every Rust-generated vector.
  final dhKey = Uint8List.fromList(List.generate(32, (i) => i));
  const dhHex = '000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f';

  group('wire format v1 vectors (generated by the Rust implementation)', () {
    final cases = <String, Map<String, dynamic>>{
      'zero counters, 3-byte ciphertext': {
        'prev': 0,
        'num': 0,
        'ct': 'aabbcc',
        'frame': '0100000028${dhHex}0000000000000000aabbcc',
      },
      'small counters, empty ciphertext': {
        'prev': 7,
        'num': 3,
        'ct': '',
        'frame': '0100000028${dhHex}0000000700000003',
      },
      'high counters exercising big-endian order': {
        'prev': 0xdeadbeef,
        'num': 0x01020304,
        'ct': 'ff' * 20,
        'frame': '0100000028${dhHex}deadbeef01020304${'ff' * 20}',
      },
    };

    cases.forEach((name, v) {
      test('serializes: $name', () {
        final msg = EncryptedMessage(
          header: MessageHeader(
            dhPublicKey: dhKey,
            previousChainLength: v['prev'] as int,
            messageNumber: v['num'] as int,
          ),
          ciphertext: _hex(v['ct'] as String),
        );
        expect(_hexOf(msg.toBytes()), equals(v['frame']));
      });

      test('parses: $name', () {
        final msg = EncryptedMessage.fromBytes(_hex(v['frame'] as String));
        expect(_hexOf(msg.header.dhPublicKey), equals(dhHex));
        expect(msg.header.previousChainLength, equals(v['prev']));
        expect(msg.header.messageNumber, equals(v['num']));
        expect(_hexOf(msg.ciphertext), equals(v['ct']));
      });
    });
  });

  group('version byte', () {
    test('is 0x01 and precedes the length', () {
      final frame = EncryptedMessage(
        header: MessageHeader(
          dhPublicKey: dhKey,
          previousChainLength: 0,
          messageNumber: 0,
        ),
        ciphertext: Uint8List(0),
      ).toBytes();

      expect(frame[0], equals(0x01));
      // header_len = 40, big-endian, at offset 1
      expect(frame.sublist(1, 5), equals([0x00, 0x00, 0x00, 0x28]));
    });

    test('rejects the pre-v1 unversioned format', () {
      // What this client used to emit: a bare big-endian header length, no version byte.
      // Its first byte is 0x00, which is why 0x01 was chosen as v1 and why this is
      // unambiguously detectable rather than silently misparsed.
      final legacy = _hex('00000028${dhHex}0000000000000000aabbcc');
      expect(
        () => EncryptedMessage.fromBytes(legacy),
        throwsA(isA<ProtocolException>()),
      );
    });

    test('rejects a future version', () {
      final future = _hex('0200000028${dhHex}0000000000000000aabbcc');
      expect(
        () => EncryptedMessage.fromBytes(future),
        throwsA(isA<ProtocolException>()),
      );
    });

    test('rejects a truncated frame', () {
      expect(
        () => EncryptedMessage.fromBytes(_hex('010000')),
        throwsA(isA<ProtocolException>()),
      );
      // Declares a 40-byte header but supplies fewer.
      expect(
        () => EncryptedMessage.fromBytes(_hex('0100000028aabb')),
        throwsA(isA<ProtocolException>()),
      );
    });
  });

  group('header binding', () {
    test('survives a base64 round trip at a non-zero buffer offset', () {
      // Regression guard for the offsetInBytes handling: base64.decode can hand back a view
      // whose offset into the underlying buffer is not zero.
      final original = EncryptedMessage(
        header: MessageHeader(
          dhPublicKey: dhKey,
          previousChainLength: 9,
          messageNumber: 11,
        ),
        ciphertext: _hex('0badc0de'),
      );
      final wire = original.toBytes();
      final padded = Uint8List(3 + wire.length)..setRange(3, 3 + wire.length, wire);
      final view = Uint8List.view(padded.buffer, 3, wire.length);

      final parsed = EncryptedMessage.fromBytes(view);
      expect(parsed.header.previousChainLength, equals(9));
      expect(parsed.header.messageNumber, equals(11));
      expect(_hexOf(parsed.ciphertext), equals('0badc0de'));
    });
  });
}
