// Known-answer tests for the wire formats that cross the Rust/Dart boundary.
//
// The vectors below were produced by the Rust implementation itself
// (backend/crates/crypto/src/double_ratchet.rs, EncryptedMessage::to_bytes), not derived by
// reading it. They exist because every other test in this suite is Dart-against-Dart: a
// round-trip passes just as happily when both sides share a bug, which is exactly how this
// client stayed on the pre-v1 format while the server moved off it.
//
// Format, per docs/adr/ADR-0011-ratchet-header-authentication.md:
//
//   version(1) || header_len:u32 BE(4) || header(40) || ciphertext
//   header = dh_public_key[32] || previous_chain_length:u32 BE || message_number:u32 BE
//
// The X3DHPrekeyMessage vectors were added by #255 and are emitted by
// `cargo test -p guardyn-crypto emit_dart_prekey_message_vectors -- --nocapture`. ADR-0011
// scoped its vectors to the ratchet frame only, and the prekey message spent that whole time
// little-endian in Rust and big-endian here, agreeing by accident because `0` is the only
// one-time key id either client sends and `0` reads the same either way.
//
// That format is now v1, per docs/spec/SRS.md - PR-97 (#261) versioned it in Rust so a
// hybrid handshake has somewhere to put its ML-KEM ciphertext, and #279 is the Dart half:
//
//   version(1)=0x01 || identity_key(32) || ephemeral_key(32) || flags(1)
//                   || [otk_id:u32 BE(4)] || [ct_len:u16 BE(2) || ct]
//
// flags bit 0x01 marks the one-time key id, 0x02 the ciphertext; 0x04-0x80 are reserved and
// rejected. The parser refuses trailing bytes, which makes the encoding canonical.
//
// The sealed sender format still has no vectors - that gap is #264.
//
// If one of these fails, Dart and Rust disagree on the wire and messages will not cross
// between clients. Do not "fix" it by editing the vector.

import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:guardyn_client/core/crypto/crypto_exceptions.dart';
import 'package:guardyn_client/core/crypto/double_ratchet.dart';
import 'package:guardyn_client/core/crypto/x3dh.dart';

Uint8List _hex(String h) {
  final out = Uint8List(h.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(h.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}

String _hexOf(Uint8List b) =>
    b.map((x) => x.toRadixString(16).padLeft(2, '0')).join();

void main() {
  // 0x00,0x01,...,0x1f - the DH public key used for every Rust-generated vector.
  final dhKey = Uint8List.fromList(List.generate(32, (i) => i));
  const dhHex =
      '000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f';

  group('wire format v1 vectors (generated by the Rust implementation)', () {
    final cases = <String, Map<String, dynamic>>{
      'zero counters, 3-byte ciphertext': {
        'prev': 0,
        'num': 0,
        'ct': 'aabbcc',
        'frame': '0100000028${dhHex}0000000000000000aabbcc',
      },
      'small counters, empty ciphertext': {
        'prev': 7,
        'num': 3,
        'ct': '',
        'frame': '0100000028${dhHex}0000000700000003',
      },
      'high counters exercising big-endian order': {
        'prev': 0xdeadbeef,
        'num': 0x01020304,
        'ct': 'ff' * 20,
        'frame': '0100000028${dhHex}deadbeef01020304${'ff' * 20}',
      },
    };

    cases.forEach((name, v) {
      test('serializes: $name', () {
        final msg = EncryptedMessage(
          header: MessageHeader(
            dhPublicKey: dhKey,
            previousChainLength: v['prev'] as int,
            messageNumber: v['num'] as int,
          ),
          ciphertext: _hex(v['ct'] as String),
        );
        expect(_hexOf(msg.toBytes()), equals(v['frame']));
      });

      test('parses: $name', () {
        final msg = EncryptedMessage.fromBytes(_hex(v['frame'] as String));
        expect(_hexOf(msg.header.dhPublicKey), equals(dhHex));
        expect(msg.header.previousChainLength, equals(v['prev']));
        expect(msg.header.messageNumber, equals(v['num']));
        expect(_hexOf(msg.ciphertext), equals(v['ct']));
      });
    });
  });

  group('version byte', () {
    test('is 0x01 and precedes the length', () {
      final frame = EncryptedMessage(
        header: MessageHeader(
          dhPublicKey: dhKey,
          previousChainLength: 0,
          messageNumber: 0,
        ),
        ciphertext: Uint8List(0),
      ).toBytes();

      expect(frame[0], equals(0x01));
      // header_len = 40, big-endian, at offset 1
      expect(frame.sublist(1, 5), equals([0x00, 0x00, 0x00, 0x28]));
    });

    test('rejects the pre-v1 unversioned format', () {
      // What this client used to emit: a bare big-endian header length, no version byte.
      // Its first byte is 0x00, which is why 0x01 was chosen as v1 and why this is
      // unambiguously detectable rather than silently misparsed.
      final legacy = _hex('00000028${dhHex}0000000000000000aabbcc');
      expect(
        () => EncryptedMessage.fromBytes(legacy),
        throwsA(isA<ProtocolException>()),
      );
    });

    test('rejects a future version', () {
      final future = _hex('0200000028${dhHex}0000000000000000aabbcc');
      expect(
        () => EncryptedMessage.fromBytes(future),
        throwsA(isA<ProtocolException>()),
      );
    });

    test('rejects a truncated frame', () {
      expect(
        () => EncryptedMessage.fromBytes(_hex('010000')),
        throwsA(isA<ProtocolException>()),
      );
      // Declares a 40-byte header but supplies fewer.
      expect(
        () => EncryptedMessage.fromBytes(_hex('0100000028aabb')),
        throwsA(isA<ProtocolException>()),
      );
    });
  });

  group('header binding', () {
    test('survives a base64 round trip at a non-zero buffer offset', () {
      // Regression guard for the offsetInBytes handling: base64.decode can hand back a view
      // whose offset into the underlying buffer is not zero.
      final original = EncryptedMessage(
        header: MessageHeader(
          dhPublicKey: dhKey,
          previousChainLength: 9,
          messageNumber: 11,
        ),
        ciphertext: _hex('0badc0de'),
      );
      final wire = original.toBytes();
      final padded = Uint8List(3 + wire.length)
        ..setRange(3, 3 + wire.length, wire);
      final view = Uint8List.view(padded.buffer, 3, wire.length);

      final parsed = EncryptedMessage.fromBytes(view);
      expect(parsed.header.previousChainLength, equals(9));
      expect(parsed.header.messageNumber, equals(11));
      expect(_hexOf(parsed.ciphertext), equals('0badc0de'));
    });
  });

  group('x3dh prekey message vectors (generated by the Rust implementation)', () {
    // Emitted verbatim by backend/crates/crypto/src/x3dh.rs, test
    // emit_dart_prekey_message_vectors. `ik` and `ek` are the repeated fill byte of the
    // 32-byte identity and ephemeral keys; `frame` is the whole v1 frame.
    //
    // Assert on `frame` directly. This file used to store a `tail` and rebuild the frame as
    // ik + ek + tail, which hides a layout change - the reconstruction encodes the very
    // offsets under test, so moving a field could leave every assertion passing.
    final cases = <String, Map<String, dynamic>>{
      'no_otk': {
        'ik': '01',
        'ek': '02',
        'otkId': null,
        'pqCiphertext': null,
        'frame':
            '010101010101010101010101010101010101010101010101010101010101010101020202020202020202020202020202020202020202020202020202020202020200',
      },
      // The id every client sends today, and the reason the endianness split in #255 stayed
      // invisible: 0 reads the same either way.
      'otk_id_zero': {
        'ik': '03',
        'ek': '04',
        'otkId': 0,
        'pqCiphertext': null,
        'frame':
            '01030303030303030303030303030303030303030303030303030303030303030304040404040404040404040404040404040404040404040404040404040404040100000000',
      },
      // The discriminating case: big-endian writes 00000001, little-endian 01000000.
      'otk_id_one': {
        'ik': '05',
        'ek': '06',
        'otkId': 1,
        'pqCiphertext': null,
        'frame':
            '01050505050505050505050505050505050505050505050505050505050505050506060606060606060606060606060606060606060606060606060606060606060100000001',
      },
      // Fully asymmetric, so any byte permutation fails, not only a full reversal.
      'otk_id_asymmetric': {
        'ik': '07',
        'ek': '08',
        'otkId': 16909060,
        'pqCiphertext': null,
        'frame':
            '01070707070707070707070707070707070707070707070707070707070707070708080808080808080808080808080808080808080808080808080808080808080101020304',
      },
      'otk_id_max': {
        'ik': '09',
        'ek': '0a',
        'otkId': 4294967295,
        'pqCiphertext': null,
        'frame':
            '0109090909090909090909090909090909090909090909090909090909090909090a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a01ffffffff',
      },
      // A hybrid handshake against a bundle with no one-time key: flag 0x02 alone, so the
      // ciphertext must sit immediately after the flags byte rather than at a fixed offset.
      'pq_only': {
        'ik': '0b',
        'ek': '0c',
        'otkId': null,
        'pqCiphertext': 'aaaaaaaa',
        'frame':
            '010b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c0c020004aaaaaaaa',
      },
      // Both optional fields present. This is the vector that pins their order - a reader
      // that took the ciphertext before the one-time key id would satisfy every other
      // vector here.
      'otk_and_pq': {
        'ik': '0d',
        'ek': '0e',
        'otkId': 7,
        'pqCiphertext': 'bbbbbbbb',
        'frame':
            '010d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0d0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e0e03000000070004bbbbbbbb',
      },
    };

    cases.forEach((name, c) {
      final ikHex = (c['ik'] as String) * 32;
      final ekHex = (c['ek'] as String) * 32;
      final frame = c['frame'] as String;
      final pqHex = c['pqCiphertext'] as String?;

      test('serializes: $name', () {
        final msg = X3DHPrekeyMessage(
          senderIdentityKey: _hex(ikHex),
          ephemeralKey: _hex(ekHex),
          usedOneTimePreKeyId: c['otkId'] as int?,
          pqCiphertext: pqHex == null ? null : _hex(pqHex),
        );
        expect(_hexOf(msg.toBytes()), equals(frame));
      });

      test('parses: $name', () {
        final parsed = X3DHPrekeyMessage.fromBytes(_hex(frame));
        expect(_hexOf(parsed.senderIdentityKey), equals(ikHex));
        expect(_hexOf(parsed.ephemeralKey), equals(ekHex));
        expect(parsed.usedOneTimePreKeyId, equals(c['otkId'] as int?));
        expect(
          parsed.pqCiphertext == null ? null : _hexOf(parsed.pqCiphertext!),
          equals(pqHex),
        );
      });
    });

    test('a one-time key id is read in network byte order, not host order', () {
      // The whole of #255 in one assertion. Reading these four bytes little-endian yields
      // 16777216 rather than 1, and X3DHProtocol.completeKeyAgreement then fails to find
      // the prekey - or, worse, finds a different one and derives a secret that differs
      // only at the first AEAD tag check.
      final frame = _hex("01${'05' * 32}${'06' * 32}0100000001");
      expect(X3DHPrekeyMessage.fromBytes(frame).usedOneTimePreKeyId, equals(1));
    });

    test('the ML-KEM ciphertext length is read in network byte order', () {
      // 1088 == 0x0440. Read little-endian it is 16388, which overruns the frame and would
      // surface as a truncation error rather than a wrong key - but at 0x0101 lengths both
      // readings are valid and the responder would decapsulate the wrong bytes.
      final ct = 'cd' * 1088;
      final frame = _hex("01${'11' * 32}${'22' * 32}020440$ct");
      final parsed = X3DHPrekeyMessage.fromBytes(frame);
      expect(parsed.pqCiphertext, isNotNull);
      expect(parsed.pqCiphertext!.length, equals(1088));
      expect(_hexOf(parsed.pqCiphertext!), equals(ct));
    });

    // The strict-parser cases, ported from prekey_message_parser_rejects_every_malformed_frame
    // in backend/crates/crypto/src/x3dh.rs. Porting the rejections matters as much as porting
    // the vectors: a lenient parser accepts everything the vectors assert and is still wrong.
    group('rejects malformed frames', () {
      // otk_and_pq: version, both keys, flags 0x03, id 7, ct_len 4, four 0xbb bytes.
      final valid = _hex("01${'0d' * 32}${'0e' * 32}03000000070004bbbbbbbb");

      test('the baseline frame is valid', () {
        expect(X3DHPrekeyMessage.fromBytes(valid).usedOneTimePreKeyId, 7);
      });

      void rejects(String label, Uint8List bytes) {
        test(label, () {
          expect(
            () => X3DHPrekeyMessage.fromBytes(bytes),
            throwsA(isA<ProtocolException>()),
            reason: '$label: accepted a frame it should refuse',
          );
        });
      }

      Uint8List tamper(int index, int value) {
        final copy = Uint8List.fromList(valid);
        copy[index] = value;
        return copy;
      }

      rejects('truncated below the minimum', valid.sublist(0, 65));

      // A v0 frame. Its first byte is an Ed25519 key byte, so it is only ever 0x01 by
      // coincidence - which is why v1 is a hard break with no fallback.
      rejects('version 0', tamper(0, 0x00));
      rejects('a version from the future', tamper(0, 0x02));

      // Reserved flag bits. Reading these as "absent" is the v0 defect that made the format
      // unextendable, so every one must be an error rather than a shrug.
      for (final bit in [0x04, 0x08, 0x10, 0x20, 0x40, 0x80]) {
        rejects(
          'reserved flag bit 0x${bit.toRadixString(16).padLeft(2, '0')}',
          tamper(65, valid[65] | bit),
        );
      }

      rejects('one-time key id truncated', valid.sublist(0, 68));
      rejects('ciphertext length truncated', valid.sublist(0, 71));

      final overlong = Uint8List.fromList(valid);
      overlong[70] = 0xff;
      overlong[71] = 0xff;
      rejects('ciphertext length exceeds the frame', overlong);

      final emptyCt = Uint8List.fromList(valid.sublist(0, 72));
      emptyCt[70] = 0x00;
      emptyCt[71] = 0x00;
      rejects('ciphertext declared empty', emptyCt);

      // The defect this version exists to close: extra bytes after a complete frame. v0
      // accepted these silently, so an ML-KEM ciphertext appended to a v0 frame vanished and
      // the responder derived a classical secret against the initiator's hybrid one.
      rejects('one trailing byte', Uint8List.fromList([...valid, 0x00]));
    });

    test('every accepted frame re-encodes to itself', () {
      // Canonicality. A parser that cannot lose bytes cannot have the v0 defect, and this is
      // the property the Rust fuzz target asserts on every accepted input.
      for (final c in cases.values) {
        final frame = c['frame'] as String;
        final parsed = X3DHPrekeyMessage.fromBytes(_hex(frame));
        expect(_hexOf(parsed.toBytes()), equals(frame));
      }
    });

    test('an out-of-range ML-KEM ciphertext is refused on encode', () {
      // An empty ciphertext would give "no ciphertext" a second encoding and break
      // canonicality; anything above 0xffff cannot be length-prefixed at all.
      Uint8List frameWith(int length) => X3DHPrekeyMessage(
        senderIdentityKey: _hex('11' * 32),
        ephemeralKey: _hex('22' * 32),
        pqCiphertext: Uint8List(length),
      ).toBytes();

      expect(() => frameWith(0), throwsA(isA<ProtocolException>()));
      expect(() => frameWith(0x10000), throwsA(isA<ProtocolException>()));
      expect(frameWith(0xffff).length, equals(66 + 2 + 0xffff));
    });
  });
}
