// Known-answer tests for the wire formats that cross the Rust/Dart boundary.
//
// The vectors below were produced by the Rust implementation itself
// (backend/crates/crypto/src/double_ratchet.rs, EncryptedMessage::to_bytes), not derived by
// reading it. They exist because every other test in this suite is Dart-against-Dart: a
// round-trip passes just as happily when both sides share a bug, which is exactly how this
// client stayed on the pre-v1 format while the server moved off it.
//
// Format, per docs/adr/ADR-0011-ratchet-header-authentication.md:
//
//   version(1) || header_len:u32 BE(4) || header(40) || ciphertext
//   header = dh_public_key[32] || previous_chain_length:u32 BE || message_number:u32 BE
//
// The X3DHPrekeyMessage vectors were added by #255 and are emitted by
// `cargo test -p guardyn-crypto emit_dart_prekey_message_vectors -- --nocapture`. ADR-0011
// scoped its vectors to the ratchet frame only, and the prekey message spent that whole time
// little-endian in Rust and big-endian here, agreeing by accident because `0` is the only
// one-time key id either client sends and `0` reads the same either way.
//
//   identity_key(32) || ephemeral_key(32) || has_otpk(1) || otpk_id:u32 BE(4 if has_otpk)
//
// The sealed sender format still has no vectors - that gap is #264.
//
// If one of these fails, Dart and Rust disagree on the wire and messages will not cross
// between clients. Do not "fix" it by editing the vector.

import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:guardyn_client/core/crypto/crypto_exceptions.dart';
import 'package:guardyn_client/core/crypto/double_ratchet.dart';
import 'package:guardyn_client/core/crypto/x3dh.dart';

Uint8List _hex(String h) {
  final out = Uint8List(h.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(h.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}

String _hexOf(Uint8List b) =>
    b.map((x) => x.toRadixString(16).padLeft(2, '0')).join();

void main() {
  // 0x00,0x01,...,0x1f - the DH public key used for every Rust-generated vector.
  final dhKey = Uint8List.fromList(List.generate(32, (i) => i));
  const dhHex = '000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f';

  group('wire format v1 vectors (generated by the Rust implementation)', () {
    final cases = <String, Map<String, dynamic>>{
      'zero counters, 3-byte ciphertext': {
        'prev': 0,
        'num': 0,
        'ct': 'aabbcc',
        'frame': '0100000028${dhHex}0000000000000000aabbcc',
      },
      'small counters, empty ciphertext': {
        'prev': 7,
        'num': 3,
        'ct': '',
        'frame': '0100000028${dhHex}0000000700000003',
      },
      'high counters exercising big-endian order': {
        'prev': 0xdeadbeef,
        'num': 0x01020304,
        'ct': 'ff' * 20,
        'frame': '0100000028${dhHex}deadbeef01020304${'ff' * 20}',
      },
    };

    cases.forEach((name, v) {
      test('serializes: $name', () {
        final msg = EncryptedMessage(
          header: MessageHeader(
            dhPublicKey: dhKey,
            previousChainLength: v['prev'] as int,
            messageNumber: v['num'] as int,
          ),
          ciphertext: _hex(v['ct'] as String),
        );
        expect(_hexOf(msg.toBytes()), equals(v['frame']));
      });

      test('parses: $name', () {
        final msg = EncryptedMessage.fromBytes(_hex(v['frame'] as String));
        expect(_hexOf(msg.header.dhPublicKey), equals(dhHex));
        expect(msg.header.previousChainLength, equals(v['prev']));
        expect(msg.header.messageNumber, equals(v['num']));
        expect(_hexOf(msg.ciphertext), equals(v['ct']));
      });
    });
  });

  group('version byte', () {
    test('is 0x01 and precedes the length', () {
      final frame = EncryptedMessage(
        header: MessageHeader(
          dhPublicKey: dhKey,
          previousChainLength: 0,
          messageNumber: 0,
        ),
        ciphertext: Uint8List(0),
      ).toBytes();

      expect(frame[0], equals(0x01));
      // header_len = 40, big-endian, at offset 1
      expect(frame.sublist(1, 5), equals([0x00, 0x00, 0x00, 0x28]));
    });

    test('rejects the pre-v1 unversioned format', () {
      // What this client used to emit: a bare big-endian header length, no version byte.
      // Its first byte is 0x00, which is why 0x01 was chosen as v1 and why this is
      // unambiguously detectable rather than silently misparsed.
      final legacy = _hex('00000028${dhHex}0000000000000000aabbcc');
      expect(
        () => EncryptedMessage.fromBytes(legacy),
        throwsA(isA<ProtocolException>()),
      );
    });

    test('rejects a future version', () {
      final future = _hex('0200000028${dhHex}0000000000000000aabbcc');
      expect(
        () => EncryptedMessage.fromBytes(future),
        throwsA(isA<ProtocolException>()),
      );
    });

    test('rejects a truncated frame', () {
      expect(
        () => EncryptedMessage.fromBytes(_hex('010000')),
        throwsA(isA<ProtocolException>()),
      );
      // Declares a 40-byte header but supplies fewer.
      expect(
        () => EncryptedMessage.fromBytes(_hex('0100000028aabb')),
        throwsA(isA<ProtocolException>()),
      );
    });
  });

  group('header binding', () {
    test('survives a base64 round trip at a non-zero buffer offset', () {
      // Regression guard for the offsetInBytes handling: base64.decode can hand back a view
      // whose offset into the underlying buffer is not zero.
      final original = EncryptedMessage(
        header: MessageHeader(
          dhPublicKey: dhKey,
          previousChainLength: 9,
          messageNumber: 11,
        ),
        ciphertext: _hex('0badc0de'),
      );
      final wire = original.toBytes();
      final padded = Uint8List(3 + wire.length)..setRange(3, 3 + wire.length, wire);
      final view = Uint8List.view(padded.buffer, 3, wire.length);

      final parsed = EncryptedMessage.fromBytes(view);
      expect(parsed.header.previousChainLength, equals(9));
      expect(parsed.header.messageNumber, equals(11));
      expect(_hexOf(parsed.ciphertext), equals('0badc0de'));
    });
  });

  group('x3dh prekey message vectors (generated by the Rust implementation)', () {
    // Emitted by backend/crates/crypto/src/x3dh.rs, test emit_dart_prekey_message_vectors.
    // `ik` and `ek` are the repeated fill byte of the 32-byte identity and ephemeral keys.
    final cases = <String, Map<String, dynamic>>{
      'no_otk': {'ik': '01', 'ek': '02', 'otkId': null, 'tail': '00'},
      // The id every client sends today, and the reason the split stayed invisible.
      'otk_id_zero': {'ik': '03', 'ek': '04', 'otkId': 0, 'tail': '0100000000'},
      // The discriminating case: big-endian writes 00000001, little-endian 01000000.
      'otk_id_one': {'ik': '05', 'ek': '06', 'otkId': 1, 'tail': '0100000001'},
      // Fully asymmetric, so any byte permutation fails, not only a full reversal.
      'otk_id_asymmetric': {
        'ik': '07',
        'ek': '08',
        'otkId': 16909060,
        'tail': '0101020304',
      },
      'otk_id_max': {
        'ik': '09',
        'ek': '0a',
        'otkId': 4294967295,
        'tail': '01ffffffff',
      },
    };

    cases.forEach((name, c) {
      final ikHex = (c['ik'] as String) * 32;
      final ekHex = (c['ek'] as String) * 32;
      final frame = ikHex + ekHex + (c['tail'] as String);

      test('serializes: $name', () {
        final msg = X3DHPrekeyMessage(
          senderIdentityKey: _hex(ikHex),
          ephemeralKey: _hex(ekHex),
          usedOneTimePreKeyId: c['otkId'] as int?,
        );
        expect(_hexOf(msg.toBytes()), equals(frame));
      });

      test('parses: $name', () {
        final parsed = X3DHPrekeyMessage.fromBytes(_hex(frame));
        expect(_hexOf(parsed.senderIdentityKey), equals(ikHex));
        expect(_hexOf(parsed.ephemeralKey), equals(ekHex));
        expect(parsed.usedOneTimePreKeyId, equals(c['otkId'] as int?));
      });
    });

    test('a one-time key id is read in network byte order, not host order', () {
      // The whole of #255 in one assertion. Reading these four bytes little-endian yields
      // 16777216 rather than 1, and X3DHProtocol.completeKeyAgreement then fails to find
      // the prekey - or, worse, finds a different one and derives a secret that differs
      // only at the first AEAD tag check.
      final frame = _hex("${'05' * 32}${'06' * 32}0100000001");
      expect(X3DHPrekeyMessage.fromBytes(frame).usedOneTimePreKeyId, equals(1));
    });
  });
}
