// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendMessageRequest {
    /// Authentication
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// Target user UUID
    #[prost(string, tag = "2")]
    pub recipient_user_id: ::prost::alloc::string::String,
    /// Target device UUID (optional, if not set - all devices)
    #[prost(string, tag = "3")]
    pub recipient_device_id: ::prost::alloc::string::String,
    /// Encrypted message content (Double Ratchet encrypted)
    #[prost(bytes = "vec", tag = "4")]
    pub encrypted_content: ::prost::alloc::vec::Vec<u8>,
    /// Message metadata
    #[prost(enumeration = "MessageType", tag = "5")]
    pub message_type: i32,
    /// Client-generated UUID for deduplication
    #[prost(string, tag = "6")]
    pub client_message_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "7")]
    pub client_timestamp: ::core::option::Option<super::common::Timestamp>,
    /// Optional: media attachment reference
    ///
    /// Reference to media uploaded via Media Service
    #[prost(string, tag = "8")]
    pub media_id: ::prost::alloc::string::String,
    /// Recipient username for display (used in conversation list)
    #[prost(string, tag = "9")]
    pub recipient_username: ::prost::alloc::string::String,
    /// X3DH prekey data for first message (allows recipient to create responder session)
    /// Base64-encoded X3DHPrekeyMessage containing: sender_identity_key, ephemeral_key, used_otpk_id
    #[prost(string, tag = "10")]
    pub x3dh_prekey: ::prost::alloc::string::String,
    /// Phase 2: Reply/Quote support
    #[prost(message, optional, tag = "11")]
    pub thread_reference: ::core::option::Option<ThreadReference>,
    /// Phase 2: Voice message metadata
    #[prost(message, optional, tag = "12")]
    pub voice_metadata: ::core::option::Option<VoiceMessageMetadata>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendMessageResponse {
    #[prost(oneof = "send_message_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<send_message_response::Result>,
}
/// Nested message and enum types in `SendMessageResponse`.
pub mod send_message_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::SendMessageSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendMessageSuccess {
    /// Server-generated UUID
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub server_timestamp: ::core::option::Option<super::common::Timestamp>,
    #[prost(enumeration = "DeliveryStatus", tag = "3")]
    pub delivery_status: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReceiveMessagesRequest {
    /// Authentication
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// If true, sends offline messages first
    #[prost(bool, tag = "2")]
    pub include_history: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Message {
    /// Server UUID
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub sender_user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub sender_device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub recipient_user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub recipient_device_id: ::prost::alloc::string::String,
    /// Encrypted content
    #[prost(bytes = "vec", tag = "6")]
    pub encrypted_content: ::prost::alloc::vec::Vec<u8>,
    /// Metadata
    #[prost(enumeration = "MessageType", tag = "7")]
    pub message_type: i32,
    #[prost(string, tag = "8")]
    pub client_message_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "9")]
    pub client_timestamp: ::core::option::Option<super::common::Timestamp>,
    #[prost(message, optional, tag = "10")]
    pub server_timestamp: ::core::option::Option<super::common::Timestamp>,
    /// Delivery tracking
    #[prost(enumeration = "DeliveryStatus", tag = "11")]
    pub delivery_status: i32,
    /// Media reference
    #[prost(string, tag = "12")]
    pub media_id: ::prost::alloc::string::String,
    /// Deletion flag
    #[prost(bool, tag = "13")]
    pub is_deleted: bool,
    /// X3DH prekey data for first message (allows recipient to create responder session)
    #[prost(string, tag = "14")]
    pub x3dh_prekey: ::prost::alloc::string::String,
    /// Phase 2: Reply/Quote support
    #[prost(message, optional, tag = "15")]
    pub thread_reference: ::core::option::Option<ThreadReference>,
    /// Phase 2: Forward support
    #[prost(message, optional, tag = "16")]
    pub forward_info: ::core::option::Option<ForwardInfo>,
    /// Phase 2: Edit tracking
    #[prost(int32, tag = "17")]
    pub edit_version: i32,
    #[prost(message, optional, tag = "18")]
    pub last_edited_at: ::core::option::Option<super::common::Timestamp>,
    /// Phase 2: Voice message metadata
    #[prost(message, optional, tag = "19")]
    pub voice_metadata: ::core::option::Option<VoiceMessageMetadata>,
    /// Phase 2: Reactions summary (aggregated)
    #[prost(message, repeated, tag = "20")]
    pub reaction_summaries: ::prost::alloc::vec::Vec<ReactionSummary>,
}
/// Aggregated reaction count for UI display
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReactionSummary {
    #[prost(string, tag = "1")]
    pub emoji: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub count: i32,
    /// Did current user react with this emoji?
    #[prost(bool, tag = "3")]
    pub user_reacted: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMessagesRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// User ID of the conversation partner
    #[prost(string, tag = "2")]
    pub conversation_user_id: ::prost::alloc::string::String,
    /// Conversation ID (alternative to conversation_user_id)
    #[prost(string, tag = "6")]
    pub conversation_id: ::prost::alloc::string::String,
    /// Pagination
    #[prost(message, optional, tag = "3")]
    pub pagination: ::core::option::Option<super::common::PaginationRequest>,
    /// Simple limit (alternative to pagination)
    #[prost(int32, tag = "7")]
    pub limit: i32,
    /// Time range filtering
    #[prost(message, optional, tag = "4")]
    pub start_time: ::core::option::Option<super::common::Timestamp>,
    #[prost(message, optional, tag = "5")]
    pub end_time: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMessagesResponse {
    #[prost(oneof = "get_messages_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<get_messages_response::Result>,
}
/// Nested message and enum types in `GetMessagesResponse`.
pub mod get_messages_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::GetMessagesSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMessagesSuccess {
    #[prost(message, repeated, tag = "1")]
    pub messages: ::prost::alloc::vec::Vec<Message>,
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<super::common::PaginationResponse>,
    /// True if there are more messages available
    #[prost(bool, tag = "3")]
    pub has_more: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationsRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// Max results (default: 50, max: 100)
    #[prost(uint32, tag = "2")]
    pub limit: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationsResponse {
    #[prost(oneof = "get_conversations_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<get_conversations_response::Result>,
}
/// Nested message and enum types in `GetConversationsResponse`.
pub mod get_conversations_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::GetConversationsSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetConversationsSuccess {
    #[prost(message, repeated, tag = "1")]
    pub conversations: ::prost::alloc::vec::Vec<Conversation>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Conversation {
    #[prost(string, tag = "1")]
    pub conversation_id: ::prost::alloc::string::String,
    /// The other user in the conversation
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    /// Username of the other user
    #[prost(string, tag = "3")]
    pub username: ::prost::alloc::string::String,
    /// Last message in conversation
    #[prost(message, optional, tag = "4")]
    pub last_message: ::core::option::Option<Message>,
    /// Number of unread messages
    #[prost(uint32, tag = "5")]
    pub unread_count: u32,
    /// Last activity timestamp
    #[prost(message, optional, tag = "6")]
    pub updated_at: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarkAsReadRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// UUIDs of messages to mark as read
    #[prost(string, repeated, tag = "2")]
    pub message_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MarkAsReadResponse {
    #[prost(oneof = "mark_as_read_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<mark_as_read_response::Result>,
}
/// Nested message and enum types in `MarkAsReadResponse`.
pub mod mark_as_read_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::MarkAsReadSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MarkAsReadSuccess {
    #[prost(uint32, tag = "1")]
    pub messages_marked: u32,
    /// Number of messages marked (alternative field name)
    #[prost(int32, tag = "2")]
    pub marked_count: i32,
    /// Server timestamp of operation
    #[prost(message, optional, tag = "3")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteMessageRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// UUID
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
    /// Conversation ID (required for ScyllaDB deletion)
    #[prost(string, tag = "4")]
    pub conversation_id: ::prost::alloc::string::String,
    /// If true, deletes for all participants
    #[prost(bool, tag = "3")]
    pub delete_for_everyone: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteMessageResponse {
    #[prost(oneof = "delete_message_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<delete_message_response::Result>,
}
/// Nested message and enum types in `DeleteMessageResponse`.
pub mod delete_message_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::DeleteMessageSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteMessageSuccess {
    #[prost(bool, tag = "1")]
    pub deleted: bool,
    /// Echo back the message ID
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
    /// Server timestamp of deletion
    #[prost(message, optional, tag = "3")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClearChatRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// Conversation to clear
    #[prost(string, tag = "2")]
    pub conversation_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClearChatResponse {
    #[prost(oneof = "clear_chat_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<clear_chat_response::Result>,
}
/// Nested message and enum types in `ClearChatResponse`.
pub mod clear_chat_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::ClearChatSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ClearChatSuccess {
    /// Number of messages deleted
    #[prost(uint32, tag = "1")]
    pub deleted_count: u32,
    /// Server timestamp of operation
    #[prost(message, optional, tag = "2")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TypingIndicatorRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub recipient_user_id: ::prost::alloc::string::String,
    /// true = started typing, false = stopped typing
    #[prost(bool, tag = "3")]
    pub is_typing: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TypingIndicatorResponse {
    #[prost(oneof = "typing_indicator_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<typing_indicator_response::Result>,
}
/// Nested message and enum types in `TypingIndicatorResponse`.
pub mod typing_indicator_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::TypingIndicatorSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TypingIndicatorSuccess {
    #[prost(bool, tag = "1")]
    pub sent: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateGroupRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub group_name: ::prost::alloc::string::String,
    /// Initial members
    #[prost(string, repeated, tag = "3")]
    pub member_user_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// MLS group state (encrypted with OpenMLS)
    #[prost(bytes = "vec", tag = "4")]
    pub mls_group_state: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateGroupResponse {
    #[prost(oneof = "create_group_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<create_group_response::Result>,
}
/// Nested message and enum types in `CreateGroupResponse`.
pub mod create_group_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::CreateGroupSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateGroupSuccess {
    /// UUID
    #[prost(string, tag = "1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub created_at: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddGroupMemberRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub member_user_id: ::prost::alloc::string::String,
    /// Device ID for MLS key package fetching
    #[prost(string, tag = "4")]
    pub member_device_id: ::prost::alloc::string::String,
    /// Updated MLS group state
    #[prost(bytes = "vec", tag = "5")]
    pub mls_group_state: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddGroupMemberResponse {
    #[prost(oneof = "add_group_member_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<add_group_member_response::Result>,
}
/// Nested message and enum types in `AddGroupMemberResponse`.
pub mod add_group_member_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::AddGroupMemberSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AddGroupMemberSuccess {
    #[prost(bool, tag = "1")]
    pub added: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveGroupMemberRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub member_user_id: ::prost::alloc::string::String,
    /// Updated MLS group state
    #[prost(bytes = "vec", tag = "4")]
    pub mls_group_state: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveGroupMemberResponse {
    #[prost(oneof = "remove_group_member_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<remove_group_member_response::Result>,
}
/// Nested message and enum types in `RemoveGroupMemberResponse`.
pub mod remove_group_member_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::RemoveGroupMemberSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RemoveGroupMemberSuccess {
    #[prost(bool, tag = "1")]
    pub removed: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendGroupMessageRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub group_id: ::prost::alloc::string::String,
    /// MLS encrypted content
    #[prost(bytes = "vec", tag = "3")]
    pub encrypted_content: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "MessageType", tag = "4")]
    pub message_type: i32,
    #[prost(string, tag = "5")]
    pub client_message_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "6")]
    pub client_timestamp: ::core::option::Option<super::common::Timestamp>,
    /// Optional
    #[prost(string, tag = "7")]
    pub media_id: ::prost::alloc::string::String,
    /// Phase 2: Reply/Quote support
    #[prost(message, optional, tag = "8")]
    pub thread_reference: ::core::option::Option<ThreadReference>,
    /// Phase 2: Voice message metadata
    #[prost(message, optional, tag = "9")]
    pub voice_metadata: ::core::option::Option<VoiceMessageMetadata>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendGroupMessageResponse {
    #[prost(oneof = "send_group_message_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<send_group_message_response::Result>,
}
/// Nested message and enum types in `SendGroupMessageResponse`.
pub mod send_group_message_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::SendGroupMessageSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendGroupMessageSuccess {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub server_timestamp: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupMessagesRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub pagination: ::core::option::Option<super::common::PaginationRequest>,
    /// Simple limit (alternative to pagination)
    #[prost(int32, tag = "6")]
    pub limit: i32,
    #[prost(message, optional, tag = "4")]
    pub start_time: ::core::option::Option<super::common::Timestamp>,
    #[prost(message, optional, tag = "5")]
    pub end_time: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupMessagesResponse {
    #[prost(oneof = "get_group_messages_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<get_group_messages_response::Result>,
}
/// Nested message and enum types in `GetGroupMessagesResponse`.
pub mod get_group_messages_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::GetGroupMessagesSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupMessagesSuccess {
    #[prost(message, repeated, tag = "1")]
    pub messages: ::prost::alloc::vec::Vec<GroupMessage>,
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<super::common::PaginationResponse>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupMessage {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub sender_user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub sender_device_id: ::prost::alloc::string::String,
    /// Username of the sender for display
    #[prost(string, tag = "12")]
    pub sender_username: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "5")]
    pub encrypted_content: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "MessageType", tag = "6")]
    pub message_type: i32,
    #[prost(string, tag = "7")]
    pub client_message_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "8")]
    pub client_timestamp: ::core::option::Option<super::common::Timestamp>,
    #[prost(message, optional, tag = "9")]
    pub server_timestamp: ::core::option::Option<super::common::Timestamp>,
    #[prost(string, tag = "10")]
    pub media_id: ::prost::alloc::string::String,
    /// Soft deletion flag
    #[prost(bool, tag = "11")]
    pub is_deleted: bool,
    /// Phase 2: Reply/Quote support
    #[prost(message, optional, tag = "13")]
    pub thread_reference: ::core::option::Option<ThreadReference>,
    /// Phase 2: Forward support
    #[prost(message, optional, tag = "14")]
    pub forward_info: ::core::option::Option<ForwardInfo>,
    /// Phase 2: Edit tracking
    #[prost(int32, tag = "15")]
    pub edit_version: i32,
    #[prost(message, optional, tag = "16")]
    pub last_edited_at: ::core::option::Option<super::common::Timestamp>,
    /// Phase 2: Voice message metadata
    #[prost(message, optional, tag = "17")]
    pub voice_metadata: ::core::option::Option<VoiceMessageMetadata>,
    /// Phase 2: Reactions summary (aggregated)
    #[prost(message, repeated, tag = "18")]
    pub reaction_summaries: ::prost::alloc::vec::Vec<ReactionSummary>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupsRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// Max results (default: 50, max: 100)
    #[prost(int32, tag = "2")]
    pub limit: i32,
    /// Pagination cursor
    #[prost(string, tag = "3")]
    pub cursor: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupsResponse {
    #[prost(oneof = "get_groups_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<get_groups_response::Result>,
}
/// Nested message and enum types in `GetGroupsResponse`.
pub mod get_groups_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::GetGroupsSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupsSuccess {
    #[prost(message, repeated, tag = "1")]
    pub groups: ::prost::alloc::vec::Vec<GroupInfo>,
    #[prost(string, tag = "2")]
    pub next_cursor: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub has_more: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupInfo {
    #[prost(string, tag = "1")]
    pub group_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub creator_user_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub members: ::prost::alloc::vec::Vec<GroupMemberInfo>,
    #[prost(message, optional, tag = "5")]
    pub created_at: ::core::option::Option<super::common::Timestamp>,
    #[prost(int32, tag = "6")]
    pub member_count: i32,
    /// Optional: for preview
    #[prost(message, optional, tag = "7")]
    pub last_message: ::core::option::Option<GroupMessage>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GroupMemberInfo {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub device_id: ::prost::alloc::string::String,
    /// "owner", "admin", "member"
    #[prost(string, tag = "4")]
    pub role: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub joined_at: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupByIdRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub group_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupByIdResponse {
    #[prost(oneof = "get_group_by_id_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<get_group_by_id_response::Result>,
}
/// Nested message and enum types in `GetGroupByIdResponse`.
pub mod get_group_by_id_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::GetGroupByIdSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetGroupByIdSuccess {
    #[prost(message, optional, tag = "1")]
    pub group: ::core::option::Option<GroupInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LeaveGroupRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub group_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LeaveGroupResponse {
    #[prost(oneof = "leave_group_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<leave_group_response::Result>,
}
/// Nested message and enum types in `LeaveGroupResponse`.
pub mod leave_group_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::LeaveGroupSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LeaveGroupSuccess {
    #[prost(bool, tag = "1")]
    pub left: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Reaction {
    /// Server-generated UUID
    #[prost(string, tag = "1")]
    pub reaction_id: ::prost::alloc::string::String,
    /// Target message UUID
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
    /// User who reacted
    #[prost(string, tag = "3")]
    pub user_id: ::prost::alloc::string::String,
    /// Unicode emoji (e.g., "👍", "❤️", "😂")
    #[prost(string, tag = "4")]
    pub emoji: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub created_at: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddReactionRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// Target message UUID
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
    /// Conversation UUID (for efficient lookup)
    #[prost(string, tag = "3")]
    pub conversation_id: ::prost::alloc::string::String,
    /// Unicode emoji
    #[prost(string, tag = "4")]
    pub emoji: ::prost::alloc::string::String,
    /// True if group message
    #[prost(bool, tag = "5")]
    pub is_group: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddReactionResponse {
    #[prost(oneof = "add_reaction_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<add_reaction_response::Result>,
}
/// Nested message and enum types in `AddReactionResponse`.
pub mod add_reaction_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::AddReactionSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AddReactionSuccess {
    #[prost(message, optional, tag = "1")]
    pub reaction: ::core::option::Option<Reaction>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveReactionRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub conversation_id: ::prost::alloc::string::String,
    /// Which emoji to remove
    #[prost(string, tag = "4")]
    pub emoji: ::prost::alloc::string::String,
    #[prost(bool, tag = "5")]
    pub is_group: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveReactionResponse {
    #[prost(oneof = "remove_reaction_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<remove_reaction_response::Result>,
}
/// Nested message and enum types in `RemoveReactionResponse`.
pub mod remove_reaction_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::RemoveReactionSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RemoveReactionSuccess {
    #[prost(bool, tag = "1")]
    pub removed: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetReactionsRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub is_group: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetReactionsResponse {
    #[prost(oneof = "get_reactions_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<get_reactions_response::Result>,
}
/// Nested message and enum types in `GetReactionsResponse`.
pub mod get_reactions_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::GetReactionsSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetReactionsSuccess {
    #[prost(message, repeated, tag = "1")]
    pub reactions: ::prost::alloc::vec::Vec<Reaction>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReadReceipt {
    #[prost(string, tag = "1")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub last_read_message_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendReadReceiptRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub last_read_message_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub is_group: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendReadReceiptResponse {
    #[prost(oneof = "send_read_receipt_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<send_read_receipt_response::Result>,
}
/// Nested message and enum types in `SendReadReceiptResponse`.
pub mod send_read_receipt_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::SendReadReceiptSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SendReadReceiptSuccess {
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetReadReceiptsRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub is_group: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetReadReceiptsResponse {
    #[prost(oneof = "get_read_receipts_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<get_read_receipts_response::Result>,
}
/// Nested message and enum types in `GetReadReceiptsResponse`.
pub mod get_read_receipts_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::GetReadReceiptsSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetReadReceiptsSuccess {
    #[prost(message, repeated, tag = "1")]
    pub receipts: ::prost::alloc::vec::Vec<ReadReceipt>,
}
/// Thread reference for replies/quotes
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ThreadReference {
    /// Original message being replied to
    #[prost(string, tag = "1")]
    pub reply_to_message_id: ::prost::alloc::string::String,
    /// SHA-256 hash of original content (for verification)
    #[prost(string, tag = "2")]
    pub quoted_content_hash: ::prost::alloc::string::String,
    /// Original sender's user ID
    #[prost(string, tag = "3")]
    pub quoted_sender_id: ::prost::alloc::string::String,
    /// Original sender's display name (cached)
    #[prost(string, tag = "4")]
    pub quoted_sender_name: ::prost::alloc::string::String,
    /// Encrypted preview of quoted message (optional)
    #[prost(bytes = "vec", tag = "5")]
    pub encrypted_quote_preview: ::prost::alloc::vec::Vec<u8>,
}
/// Forward metadata
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ForwardInfo {
    #[prost(string, tag = "1")]
    pub original_message_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub original_sender_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub original_sender_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub original_timestamp: ::core::option::Option<super::common::Timestamp>,
    /// How many times this message has been forwarded
    #[prost(int32, tag = "5")]
    pub forward_count: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ForwardMessageRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// Message to forward
    #[prost(string, tag = "2")]
    pub source_message_id: ::prost::alloc::string::String,
    /// Source conversation
    #[prost(string, tag = "3")]
    pub source_conversation_id: ::prost::alloc::string::String,
    /// Is source a group?
    #[prost(bool, tag = "4")]
    pub source_is_group: bool,
    /// Target destination
    ///
    /// Destination conversation
    #[prost(string, tag = "5")]
    pub target_conversation_id: ::prost::alloc::string::String,
    /// Is target a group?
    #[prost(bool, tag = "6")]
    pub target_is_group: bool,
    /// Target user (for 1-on-1)
    #[prost(string, tag = "7")]
    pub target_user_id: ::prost::alloc::string::String,
    /// Re-encrypted content for target
    #[prost(bytes = "vec", tag = "8")]
    pub encrypted_content: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "9")]
    pub client_message_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ForwardMessageResponse {
    #[prost(oneof = "forward_message_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<forward_message_response::Result>,
}
/// Nested message and enum types in `ForwardMessageResponse`.
pub mod forward_message_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::ForwardMessageSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ForwardMessageSuccess {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub server_timestamp: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EditMessageRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub is_group: bool,
    /// New encrypted content
    #[prost(bytes = "vec", tag = "5")]
    pub encrypted_content: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "6")]
    pub client_timestamp: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EditMessageResponse {
    #[prost(oneof = "edit_message_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<edit_message_response::Result>,
}
/// Nested message and enum types in `EditMessageResponse`.
pub mod edit_message_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::EditMessageSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EditMessageSuccess {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    /// Incremented on each edit
    #[prost(int32, tag = "2")]
    pub edit_version: i32,
    #[prost(message, optional, tag = "3")]
    pub server_timestamp: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageEdit {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub encrypted_content: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, tag = "3")]
    pub edit_version: i32,
    #[prost(message, optional, tag = "4")]
    pub edit_timestamp: ::core::option::Option<super::common::Timestamp>,
    /// User ID who made the edit
    #[prost(string, tag = "5")]
    pub edited_by: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VoiceMessageMetadata {
    /// Reference to media in Media Service
    #[prost(string, tag = "1")]
    pub media_id: ::prost::alloc::string::String,
    /// Duration in milliseconds
    #[prost(int32, tag = "2")]
    pub duration_ms: i32,
    /// Audio waveform for UI visualization (100 samples, 0-255)
    #[prost(bytes = "vec", tag = "3")]
    pub waveform: ::prost::alloc::vec::Vec<u8>,
    /// Audio codec (e.g., "opus", "aac")
    #[prost(string, tag = "4")]
    pub codec: ::prost::alloc::string::String,
    /// Sample rate in Hz
    #[prost(int32, tag = "5")]
    pub sample_rate: i32,
    /// Bitrate in bps
    #[prost(int32, tag = "6")]
    pub bitrate: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchMessagesRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// Search query (will be applied to decrypted content client-side)
    #[prost(string, tag = "2")]
    pub query: ::prost::alloc::string::String,
    /// Filter options
    ///
    /// Optional: limit to specific conversation
    #[prost(string, tag = "3")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub is_group: bool,
    /// Optional: date range start
    #[prost(message, optional, tag = "5")]
    pub start_time: ::core::option::Option<super::common::Timestamp>,
    /// Optional: date range end
    #[prost(message, optional, tag = "6")]
    pub end_time: ::core::option::Option<super::common::Timestamp>,
    /// Optional: filter by type
    #[prost(enumeration = "MessageType", repeated, tag = "7")]
    pub message_types: ::prost::alloc::vec::Vec<i32>,
    /// Pagination
    #[prost(int32, tag = "8")]
    pub limit: i32,
    #[prost(string, tag = "9")]
    pub cursor: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchMessagesResponse {
    #[prost(oneof = "search_messages_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<search_messages_response::Result>,
}
/// Nested message and enum types in `SearchMessagesResponse`.
pub mod search_messages_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::SearchMessagesSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchMessagesSuccess {
    #[prost(message, repeated, tag = "1")]
    pub results: ::prost::alloc::vec::Vec<SearchResult>,
    #[prost(string, tag = "2")]
    pub next_cursor: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub has_more: bool,
    /// Approximate total matches
    #[prost(int32, tag = "4")]
    pub total_count: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchResult {
    #[prost(string, tag = "1")]
    pub message_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub is_group: bool,
    #[prost(string, tag = "4")]
    pub sender_user_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "5")]
    pub encrypted_content: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "6")]
    pub server_timestamp: ::core::option::Option<super::common::Timestamp>,
    #[prost(enumeration = "MessageType", tag = "7")]
    pub message_type: i32,
    /// Context for search highlighting (client will decrypt and highlight)
    ///
    /// Conversation or group name for display
    #[prost(string, tag = "8")]
    pub conversation_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DisappearingConfig {
    #[prost(string, tag = "1")]
    pub conversation_id: ::prost::alloc::string::String,
    /// 0 = disabled, else auto-delete after TTL
    #[prost(int32, tag = "2")]
    pub ttl_seconds: i32,
    /// Who configured this
    #[prost(string, tag = "3")]
    pub set_by_user_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub updated_at: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetDisappearingMessagesRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub is_group: bool,
    /// 0 = disable, common values: 86400 (1d), 604800 (7d)
    #[prost(int32, tag = "4")]
    pub ttl_seconds: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetDisappearingMessagesResponse {
    #[prost(oneof = "set_disappearing_messages_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<set_disappearing_messages_response::Result>,
}
/// Nested message and enum types in `SetDisappearingMessagesResponse`.
pub mod set_disappearing_messages_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::SetDisappearingMessagesSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetDisappearingMessagesSuccess {
    #[prost(message, optional, tag = "1")]
    pub config: ::core::option::Option<DisappearingConfig>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDisappearingConfigRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub conversation_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub is_group: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDisappearingConfigResponse {
    #[prost(oneof = "get_disappearing_config_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<get_disappearing_config_response::Result>,
}
/// Nested message and enum types in `GetDisappearingConfigResponse`.
pub mod get_disappearing_config_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::GetDisappearingConfigSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetDisappearingConfigSuccess {
    #[prost(message, optional, tag = "1")]
    pub config: ::core::option::Option<DisappearingConfig>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HealthRequest {}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MessageType {
    Text = 0,
    Image = 1,
    Video = 2,
    Audio = 3,
    File = 4,
    VoiceNote = 5,
    Location = 6,
}
impl MessageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Text => "TEXT",
            Self::Image => "IMAGE",
            Self::Video => "VIDEO",
            Self::Audio => "AUDIO",
            Self::File => "FILE",
            Self::VoiceNote => "VOICE_NOTE",
            Self::Location => "LOCATION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TEXT" => Some(Self::Text),
            "IMAGE" => Some(Self::Image),
            "VIDEO" => Some(Self::Video),
            "AUDIO" => Some(Self::Audio),
            "FILE" => Some(Self::File),
            "VOICE_NOTE" => Some(Self::VoiceNote),
            "LOCATION" => Some(Self::Location),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DeliveryStatus {
    /// Queued for delivery
    Pending = 0,
    /// Sent to recipient's device
    Sent = 1,
    /// Delivered to recipient's device
    Delivered = 2,
    /// Read by recipient
    Read = 3,
    /// Delivery failed
    Failed = 4,
}
impl DeliveryStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Pending => "PENDING",
            Self::Sent => "SENT",
            Self::Delivered => "DELIVERED",
            Self::Read => "READ",
            Self::Failed => "FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PENDING" => Some(Self::Pending),
            "SENT" => Some(Self::Sent),
            "DELIVERED" => Some(Self::Delivered),
            "READ" => Some(Self::Read),
            "FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod messaging_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct MessagingServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MessagingServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MessagingServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MessagingServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            MessagingServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Send 1-on-1 encrypted message
        pub async fn send_message(
            &mut self,
            request: impl tonic::IntoRequest<super::SendMessageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SendMessageResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/SendMessage",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.messaging.MessagingService", "SendMessage"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Receive messages (streaming from server)
        pub async fn receive_messages(
            &mut self,
            request: impl tonic::IntoRequest<super::ReceiveMessagesRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::Message>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/ReceiveMessages",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "guardyn.messaging.MessagingService",
                        "ReceiveMessages",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Get message history
        pub async fn get_messages(
            &mut self,
            request: impl tonic::IntoRequest<super::GetMessagesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetMessagesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/GetMessages",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.messaging.MessagingService", "GetMessages"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get list of conversations
        pub async fn get_conversations(
            &mut self,
            request: impl tonic::IntoRequest<super::GetConversationsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetConversationsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/GetConversations",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "guardyn.messaging.MessagingService",
                        "GetConversations",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Mark message as read (send read receipt)
        pub async fn mark_as_read(
            &mut self,
            request: impl tonic::IntoRequest<super::MarkAsReadRequest>,
        ) -> std::result::Result<
            tonic::Response<super::MarkAsReadResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/MarkAsRead",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.messaging.MessagingService", "MarkAsRead"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Delete message (for self or for everyone)
        pub async fn delete_message(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteMessageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteMessageResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/DeleteMessage",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "guardyn.messaging.MessagingService",
                        "DeleteMessage",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Send typing indicator
        pub async fn send_typing_indicator(
            &mut self,
            request: impl tonic::IntoRequest<super::TypingIndicatorRequest>,
        ) -> std::result::Result<
            tonic::Response<super::TypingIndicatorResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/SendTypingIndicator",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "guardyn.messaging.MessagingService",
                        "SendTypingIndicator",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Create group chat
        pub async fn create_group(
            &mut self,
            request: impl tonic::IntoRequest<super::CreateGroupRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateGroupResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/CreateGroup",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.messaging.MessagingService", "CreateGroup"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Add member to group
        pub async fn add_group_member(
            &mut self,
            request: impl tonic::IntoRequest<super::AddGroupMemberRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddGroupMemberResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/AddGroupMember",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "guardyn.messaging.MessagingService",
                        "AddGroupMember",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Remove member from group
        pub async fn remove_group_member(
            &mut self,
            request: impl tonic::IntoRequest<super::RemoveGroupMemberRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RemoveGroupMemberResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/RemoveGroupMember",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "guardyn.messaging.MessagingService",
                        "RemoveGroupMember",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Send group message
        pub async fn send_group_message(
            &mut self,
            request: impl tonic::IntoRequest<super::SendGroupMessageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SendGroupMessageResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/SendGroupMessage",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "guardyn.messaging.MessagingService",
                        "SendGroupMessage",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get group messages
        pub async fn get_group_messages(
            &mut self,
            request: impl tonic::IntoRequest<super::GetGroupMessagesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetGroupMessagesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/GetGroupMessages",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "guardyn.messaging.MessagingService",
                        "GetGroupMessages",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get all groups for the current user
        pub async fn get_groups(
            &mut self,
            request: impl tonic::IntoRequest<super::GetGroupsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetGroupsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/GetGroups",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.messaging.MessagingService", "GetGroups"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get group details by ID
        pub async fn get_group_by_id(
            &mut self,
            request: impl tonic::IntoRequest<super::GetGroupByIdRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetGroupByIdResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/GetGroupById",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.messaging.MessagingService", "GetGroupById"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Leave a group
        pub async fn leave_group(
            &mut self,
            request: impl tonic::IntoRequest<super::LeaveGroupRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LeaveGroupResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/LeaveGroup",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.messaging.MessagingService", "LeaveGroup"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Clear all messages in a conversation (local delete for current user)
        pub async fn clear_chat(
            &mut self,
            request: impl tonic::IntoRequest<super::ClearChatRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ClearChatResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/ClearChat",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.messaging.MessagingService", "ClearChat"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Add reaction to a message
        pub async fn add_reaction(
            &mut self,
            request: impl tonic::IntoRequest<super::AddReactionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AddReactionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/AddReaction",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.messaging.MessagingService", "AddReaction"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Remove reaction from a message
        pub async fn remove_reaction(
            &mut self,
            request: impl tonic::IntoRequest<super::RemoveReactionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RemoveReactionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/RemoveReaction",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "guardyn.messaging.MessagingService",
                        "RemoveReaction",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get all reactions for a message
        pub async fn get_reactions(
            &mut self,
            request: impl tonic::IntoRequest<super::GetReactionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetReactionsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/GetReactions",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.messaging.MessagingService", "GetReactions"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Send read receipt for a conversation
        pub async fn send_read_receipt(
            &mut self,
            request: impl tonic::IntoRequest<super::SendReadReceiptRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SendReadReceiptResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/SendReadReceipt",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "guardyn.messaging.MessagingService",
                        "SendReadReceipt",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get read receipts for a conversation (who read what)
        pub async fn get_read_receipts(
            &mut self,
            request: impl tonic::IntoRequest<super::GetReadReceiptsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetReadReceiptsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/GetReadReceipts",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "guardyn.messaging.MessagingService",
                        "GetReadReceipts",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Forward a message to another conversation
        pub async fn forward_message(
            &mut self,
            request: impl tonic::IntoRequest<super::ForwardMessageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ForwardMessageResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/ForwardMessage",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "guardyn.messaging.MessagingService",
                        "ForwardMessage",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Edit a previously sent message
        pub async fn edit_message(
            &mut self,
            request: impl tonic::IntoRequest<super::EditMessageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::EditMessageResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/EditMessage",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.messaging.MessagingService", "EditMessage"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Search messages (returns encrypted content for client-side search)
        pub async fn search_messages(
            &mut self,
            request: impl tonic::IntoRequest<super::SearchMessagesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SearchMessagesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/SearchMessages",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "guardyn.messaging.MessagingService",
                        "SearchMessages",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Set disappearing messages config for a conversation
        pub async fn set_disappearing_messages(
            &mut self,
            request: impl tonic::IntoRequest<super::SetDisappearingMessagesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetDisappearingMessagesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/SetDisappearingMessages",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "guardyn.messaging.MessagingService",
                        "SetDisappearingMessages",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get disappearing messages config
        pub async fn get_disappearing_config(
            &mut self,
            request: impl tonic::IntoRequest<super::GetDisappearingConfigRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetDisappearingConfigResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/GetDisappearingConfig",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "guardyn.messaging.MessagingService",
                        "GetDisappearingConfig",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Health check
        pub async fn health(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::HealthStatus>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.messaging.MessagingService/Health",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.messaging.MessagingService", "Health"));
            self.inner.unary(req, path, codec).await
        }
    }
}
