// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterRequest {
    /// Unique username (3-32 chars, alphanumeric + underscore)
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    /// Password (min 12 chars, will be hashed with Argon2id)
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    /// Email for recovery (optional in MVP)
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    /// Device information
    ///
    /// e.g., "iPhone 15 Pro", "Desktop Chrome"
    #[prost(string, tag = "4")]
    pub device_name: ::prost::alloc::string::String,
    /// "ios", "android", "web", "desktop"
    #[prost(string, tag = "5")]
    pub device_type: ::prost::alloc::string::String,
    /// E2EE key bundle for this device
    #[prost(message, optional, tag = "6")]
    pub key_bundle: ::core::option::Option<super::common::KeyBundle>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterResponse {
    #[prost(oneof = "register_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<register_response::Result>,
}
/// Nested message and enum types in `RegisterResponse`.
pub mod register_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::RegisterSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterSuccess {
    /// UUID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// UUID
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
    /// JWT (15 min expiry)
    #[prost(string, tag = "3")]
    pub access_token: ::prost::alloc::string::String,
    /// Expiry time in seconds (e.g., 900 for 15 min)
    #[prost(uint32, tag = "4")]
    pub access_token_expires_in: u32,
    /// JWT (30 days expiry)
    #[prost(string, tag = "5")]
    pub refresh_token: ::prost::alloc::string::String,
    /// Expiry time in seconds (e.g., 2592000 for 30 days)
    #[prost(uint32, tag = "6")]
    pub refresh_token_expires_in: u32,
    #[prost(message, optional, tag = "7")]
    pub created_at: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginRequest {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    /// Device information (new or existing)
    ///
    /// UUID (optional, if returning device)
    #[prost(string, tag = "3")]
    pub device_id: ::prost::alloc::string::String,
    /// e.g., "iPhone 15 Pro"
    #[prost(string, tag = "4")]
    pub device_name: ::prost::alloc::string::String,
    /// "ios", "android", "web", "desktop"
    #[prost(string, tag = "5")]
    pub device_type: ::prost::alloc::string::String,
    /// E2EE key bundle for this device (required if new device)
    #[prost(message, optional, tag = "6")]
    pub key_bundle: ::core::option::Option<super::common::KeyBundle>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginResponse {
    #[prost(oneof = "login_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<login_response::Result>,
}
/// Nested message and enum types in `LoginResponse`.
pub mod login_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::LoginSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginSuccess {
    /// UUID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// UUID
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
    /// JWT (15 min expiry)
    #[prost(string, tag = "3")]
    pub access_token: ::prost::alloc::string::String,
    /// Expiry time in seconds (e.g., 900 for 15 min)
    #[prost(uint32, tag = "4")]
    pub access_token_expires_in: u32,
    /// JWT (30 days expiry)
    #[prost(string, tag = "5")]
    pub refresh_token: ::prost::alloc::string::String,
    /// Expiry time in seconds (e.g., 2592000 for 30 days)
    #[prost(uint32, tag = "6")]
    pub refresh_token_expires_in: u32,
    /// User profile
    #[prost(message, optional, tag = "7")]
    pub profile: ::core::option::Option<UserProfile>,
    /// All user's devices
    #[prost(message, repeated, tag = "8")]
    pub devices: ::prost::alloc::vec::Vec<DeviceInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserProfile {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub created_at: ::core::option::Option<super::common::Timestamp>,
    #[prost(message, optional, tag = "5")]
    pub last_seen: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeviceInfo {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub device_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub device_type: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub created_at: ::core::option::Option<super::common::Timestamp>,
    #[prost(message, optional, tag = "5")]
    pub last_seen: ::core::option::Option<super::common::Timestamp>,
    /// True for the device making the request
    #[prost(bool, tag = "6")]
    pub is_current: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogoutRequest {
    /// JWT to invalidate
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// If true, logout from all devices
    #[prost(bool, tag = "2")]
    pub all_devices: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogoutResponse {
    #[prost(oneof = "logout_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<logout_response::Result>,
}
/// Nested message and enum types in `LogoutResponse`.
pub mod logout_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::LogoutSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LogoutSuccess {
    /// Number of sessions logged out
    #[prost(uint32, tag = "1")]
    pub sessions_invalidated: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RefreshTokenRequest {
    /// JWT refresh token
    #[prost(string, tag = "1")]
    pub refresh_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RefreshTokenResponse {
    #[prost(oneof = "refresh_token_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<refresh_token_response::Result>,
}
/// Nested message and enum types in `RefreshTokenResponse`.
pub mod refresh_token_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::RefreshTokenSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RefreshTokenSuccess {
    /// New JWT (15 min expiry)
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// Expiry time in seconds (e.g., 900 for 15 min)
    #[prost(uint32, tag = "2")]
    pub access_token_expires_in: u32,
    /// New refresh token (30 days expiry)
    #[prost(string, tag = "3")]
    pub refresh_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateTokenRequest {
    /// JWT to validate
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateTokenResponse {
    #[prost(oneof = "validate_token_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<validate_token_response::Result>,
}
/// Nested message and enum types in `ValidateTokenResponse`.
pub mod validate_token_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::ValidateTokenSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateTokenSuccess {
    /// UUID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// UUID
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub expires_at: ::core::option::Option<super::common::Timestamp>,
    /// User permissions/roles
    #[prost(string, repeated, tag = "4")]
    pub permissions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetKeyBundleRequest {
    /// Target user
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// Target device (optional, if not set returns any device)
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetKeyBundleResponse {
    #[prost(oneof = "get_key_bundle_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<get_key_bundle_response::Result>,
}
/// Nested message and enum types in `GetKeyBundleResponse`.
pub mod get_key_bundle_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::GetKeyBundleSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetKeyBundleSuccess {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub key_bundle: ::core::option::Option<super::common::KeyBundle>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UploadPreKeysRequest {
    /// Authentication
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// New X25519 pre-keys
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub one_time_pre_keys: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UploadPreKeysResponse {
    #[prost(oneof = "upload_pre_keys_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<upload_pre_keys_response::Result>,
}
/// Nested message and enum types in `UploadPreKeysResponse`.
pub mod upload_pre_keys_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::UploadPreKeysSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UploadPreKeysSuccess {
    #[prost(uint32, tag = "1")]
    pub keys_uploaded: u32,
    #[prost(uint32, tag = "2")]
    pub total_keys_available: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UploadMlsKeyPackageRequest {
    /// Authentication
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// Serialized MLS KeyPackage
    #[prost(bytes = "vec", tag = "2")]
    pub key_package: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UploadMlsKeyPackageResponse {
    #[prost(oneof = "upload_mls_key_package_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<upload_mls_key_package_response::Result>,
}
/// Nested message and enum types in `UploadMlsKeyPackageResponse`.
pub mod upload_mls_key_package_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::UploadMlsKeyPackageSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UploadMlsKeyPackageSuccess {
    /// Unique ID for this key package
    #[prost(string, tag = "1")]
    pub package_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub uploaded_at: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMlsKeyPackageRequest {
    /// Target user
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// Target device (optional)
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMlsKeyPackageResponse {
    #[prost(oneof = "get_mls_key_package_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<get_mls_key_package_response::Result>,
}
/// Nested message and enum types in `GetMlsKeyPackageResponse`.
pub mod get_mls_key_package_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::GetMlsKeyPackageSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetMlsKeyPackageSuccess {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
    /// Serialized MLS KeyPackage
    #[prost(bytes = "vec", tag = "3")]
    pub key_package: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "4")]
    pub package_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchUsersRequest {
    /// Authentication
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// Search query (username)
    #[prost(string, tag = "2")]
    pub query: ::prost::alloc::string::String,
    /// Max results (default: 20, max: 100)
    #[prost(uint32, tag = "3")]
    pub limit: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchUsersResponse {
    #[prost(oneof = "search_users_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<search_users_response::Result>,
}
/// Nested message and enum types in `SearchUsersResponse`.
pub mod search_users_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::SearchUsersSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SearchUsersSuccess {
    #[prost(message, repeated, tag = "1")]
    pub users: ::prost::alloc::vec::Vec<UserSearchResult>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserSearchResult {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub created_at: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserProfileRequest {
    /// UUID of the user to lookup
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserProfileResponse {
    #[prost(oneof = "get_user_profile_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<get_user_profile_response::Result>,
}
/// Nested message and enum types in `GetUserProfileResponse`.
pub mod get_user_profile_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        /// Reuse existing UserProfile message
        #[prost(message, tag = "1")]
        Success(super::UserProfile),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HealthRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteAccountRequest {
    /// Authentication - identifies the user to delete
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// Password confirmation for security
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteAccountResponse {
    #[prost(oneof = "delete_account_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<delete_account_response::Result>,
}
/// Nested message and enum types in `DeleteAccountResponse`.
pub mod delete_account_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::DeleteAccountSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteAccountSuccess {
    /// UUID of the deleted user
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// Confirmation message
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod auth_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct AuthServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AuthServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AuthServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AuthServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            AuthServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// User registration with E2EE key bundle
        pub async fn register(
            &mut self,
            request: impl tonic::IntoRequest<super::RegisterRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.auth.AuthService/Register",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.auth.AuthService", "Register"));
            self.inner.unary(req, path, codec).await
        }
        /// User login (device authentication)
        pub async fn login(
            &mut self,
            request: impl tonic::IntoRequest<super::LoginRequest>,
        ) -> std::result::Result<tonic::Response<super::LoginResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.auth.AuthService/Login",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.auth.AuthService", "Login"));
            self.inner.unary(req, path, codec).await
        }
        /// User logout (invalidate session)
        pub async fn logout(
            &mut self,
            request: impl tonic::IntoRequest<super::LogoutRequest>,
        ) -> std::result::Result<tonic::Response<super::LogoutResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.auth.AuthService/Logout",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.auth.AuthService", "Logout"));
            self.inner.unary(req, path, codec).await
        }
        /// Refresh access token using refresh token
        pub async fn refresh_token(
            &mut self,
            request: impl tonic::IntoRequest<super::RefreshTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RefreshTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.auth.AuthService/RefreshToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.auth.AuthService", "RefreshToken"));
            self.inner.unary(req, path, codec).await
        }
        /// Validate JWT token (internal service-to-service)
        pub async fn validate_token(
            &mut self,
            request: impl tonic::IntoRequest<super::ValidateTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidateTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.auth.AuthService/ValidateToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.auth.AuthService", "ValidateToken"));
            self.inner.unary(req, path, codec).await
        }
        /// Get user's key bundle for E2EE initiation
        pub async fn get_key_bundle(
            &mut self,
            request: impl tonic::IntoRequest<super::GetKeyBundleRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetKeyBundleResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.auth.AuthService/GetKeyBundle",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.auth.AuthService", "GetKeyBundle"));
            self.inner.unary(req, path, codec).await
        }
        /// Upload new pre-keys (key rotation)
        pub async fn upload_pre_keys(
            &mut self,
            request: impl tonic::IntoRequest<super::UploadPreKeysRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UploadPreKeysResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.auth.AuthService/UploadPreKeys",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.auth.AuthService", "UploadPreKeys"));
            self.inner.unary(req, path, codec).await
        }
        /// Upload MLS key package for group chat (MLS Protocol)
        pub async fn upload_mls_key_package(
            &mut self,
            request: impl tonic::IntoRequest<super::UploadMlsKeyPackageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UploadMlsKeyPackageResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.auth.AuthService/UploadMlsKeyPackage",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.auth.AuthService", "UploadMlsKeyPackage"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get MLS key package for a user (used when adding to group)
        pub async fn get_mls_key_package(
            &mut self,
            request: impl tonic::IntoRequest<super::GetMlsKeyPackageRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetMlsKeyPackageResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.auth.AuthService/GetMlsKeyPackage",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.auth.AuthService", "GetMlsKeyPackage"));
            self.inner.unary(req, path, codec).await
        }
        /// Search for users by username
        pub async fn search_users(
            &mut self,
            request: impl tonic::IntoRequest<super::SearchUsersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SearchUsersResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.auth.AuthService/SearchUsers",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.auth.AuthService", "SearchUsers"));
            self.inner.unary(req, path, codec).await
        }
        /// Get user profile by user ID (internal service-to-service)
        pub async fn get_user_profile(
            &mut self,
            request: impl tonic::IntoRequest<super::GetUserProfileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetUserProfileResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.auth.AuthService/GetUserProfile",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.auth.AuthService", "GetUserProfile"));
            self.inner.unary(req, path, codec).await
        }
        /// Delete user account and all associated data
        pub async fn delete_account(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteAccountRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteAccountResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.auth.AuthService/DeleteAccount",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.auth.AuthService", "DeleteAccount"));
            self.inner.unary(req, path, codec).await
        }
        /// Health check
        pub async fn health(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::HealthStatus>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.auth.AuthService/Health",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.auth.AuthService", "Health"));
            self.inner.unary(req, path, codec).await
        }
    }
}
