// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateStatusRequest {
    /// Authentication
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(enumeration = "UserStatus", tag = "2")]
    pub status: i32,
    /// Optional custom status message (max 100 chars)
    #[prost(string, tag = "3")]
    pub custom_status_text: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateStatusResponse {
    #[prost(oneof = "update_status_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<update_status_response::Result>,
}
/// Nested message and enum types in `UpdateStatusResponse`.
pub mod update_status_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::UpdateStatusSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UpdateStatusSuccess {
    #[prost(enumeration = "UserStatus", tag = "1")]
    pub status: i32,
    #[prost(message, optional, tag = "2")]
    pub updated_at: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetStatusRequest {
    /// Authentication
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// Target user UUID
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetStatusResponse {
    #[prost(oneof = "get_status_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<get_status_response::Result>,
}
/// Nested message and enum types in `GetStatusResponse`.
pub mod get_status_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::GetStatusSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetStatusSuccess {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(enumeration = "UserStatus", tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub custom_status_text: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub last_seen: ::core::option::Option<super::common::Timestamp>,
    /// If currently typing to the requester
    #[prost(bool, tag = "5")]
    pub is_typing: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SubscribeRequest {
    /// Authentication
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// List of users to subscribe to (max 100)
    #[prost(string, repeated, tag = "2")]
    pub user_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PresenceUpdate {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(enumeration = "UserStatus", tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub custom_status_text: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub last_seen: ::core::option::Option<super::common::Timestamp>,
    #[prost(message, optional, tag = "5")]
    pub updated_at: ::core::option::Option<super::common::Timestamp>,
    /// Typing indicator (only for 1-on-1 conversations)
    #[prost(bool, tag = "6")]
    pub is_typing: bool,
    /// User ID if typing
    #[prost(string, tag = "7")]
    pub typing_in_conversation_with: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBulkStatusRequest {
    /// Authentication
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// List of user IDs to query (max 100)
    #[prost(string, repeated, tag = "2")]
    pub user_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBulkStatusResponse {
    #[prost(oneof = "get_bulk_status_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<get_bulk_status_response::Result>,
}
/// Nested message and enum types in `GetBulkStatusResponse`.
pub mod get_bulk_status_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::GetBulkStatusSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetBulkStatusSuccess {
    #[prost(message, repeated, tag = "1")]
    pub presences: ::prost::alloc::vec::Vec<UserPresence>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserPresence {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(enumeration = "UserStatus", tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub custom_status_text: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub last_seen: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateLastSeenRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateLastSeenResponse {
    #[prost(oneof = "update_last_seen_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<update_last_seen_response::Result>,
}
/// Nested message and enum types in `UpdateLastSeenResponse`.
pub mod update_last_seen_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::UpdateLastSeenSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UpdateLastSeenSuccess {
    #[prost(message, optional, tag = "1")]
    pub last_seen: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetTypingRequest {
    /// Authentication
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// User ID of the conversation partner
    #[prost(string, tag = "2")]
    pub conversation_user_id: ::prost::alloc::string::String,
    /// true when started typing, false when stopped
    #[prost(bool, tag = "3")]
    pub is_typing: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetTypingResponse {
    #[prost(oneof = "set_typing_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<set_typing_response::Result>,
}
/// Nested message and enum types in `SetTypingResponse`.
pub mod set_typing_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::SetTypingSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetTypingSuccess {
    #[prost(bool, tag = "1")]
    pub acknowledged: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HealthRequest {}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UserStatus {
    Offline = 0,
    Online = 1,
    /// Idle for >5 minutes
    Away = 2,
    /// Mute notifications
    DoNotDisturb = 3,
    /// Appear offline to others
    Invisible = 4,
}
impl UserStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Offline => "OFFLINE",
            Self::Online => "ONLINE",
            Self::Away => "AWAY",
            Self::DoNotDisturb => "DO_NOT_DISTURB",
            Self::Invisible => "INVISIBLE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OFFLINE" => Some(Self::Offline),
            "ONLINE" => Some(Self::Online),
            "AWAY" => Some(Self::Away),
            "DO_NOT_DISTURB" => Some(Self::DoNotDisturb),
            "INVISIBLE" => Some(Self::Invisible),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod presence_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct PresenceServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl PresenceServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> PresenceServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> PresenceServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            PresenceServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Update user's online status
        pub async fn update_status(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.presence.PresenceService/UpdateStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.presence.PresenceService", "UpdateStatus"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get user's current status
        pub async fn get_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.presence.PresenceService/GetStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.presence.PresenceService", "GetStatus"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get multiple users' presence status
        pub async fn get_bulk_status(
            &mut self,
            request: impl tonic::IntoRequest<super::GetBulkStatusRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetBulkStatusResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.presence.PresenceService/GetBulkStatus",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.presence.PresenceService", "GetBulkStatus"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Subscribe to presence updates (streaming)
        pub async fn subscribe(
            &mut self,
            request: impl tonic::IntoRequest<super::SubscribeRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::PresenceUpdate>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.presence.PresenceService/Subscribe",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.presence.PresenceService", "Subscribe"),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Update last seen timestamp
        pub async fn update_last_seen(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateLastSeenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateLastSeenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.presence.PresenceService/UpdateLastSeen",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.presence.PresenceService", "UpdateLastSeen"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Send typing indicator
        pub async fn set_typing(
            &mut self,
            request: impl tonic::IntoRequest<super::SetTypingRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetTypingResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.presence.PresenceService/SetTyping",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.presence.PresenceService", "SetTyping"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Health check
        pub async fn health(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::HealthStatus>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.presence.PresenceService/Health",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.presence.PresenceService", "Health"));
            self.inner.unary(req, path, codec).await
        }
    }
}
