// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitiateCallRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(enumeration = "CallType", tag = "4")]
    pub call_type: i32,
    /// Client capabilities
    #[prost(message, optional, tag = "5")]
    pub capabilities: ::core::option::Option<ClientCapabilities>,
    #[prost(oneof = "initiate_call_request::Target", tags = "2, 3")]
    pub target: ::core::option::Option<initiate_call_request::Target>,
}
/// Nested message and enum types in `InitiateCallRequest`.
pub mod initiate_call_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Target {
        /// 1-on-1 call
        #[prost(string, tag = "2")]
        UserId(::prost::alloc::string::String),
        /// Group call
        #[prost(string, tag = "3")]
        GroupId(::prost::alloc::string::String),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientCapabilities {
    #[prost(bool, tag = "1")]
    pub supports_video: bool,
    #[prost(bool, tag = "2")]
    pub supports_screen_share: bool,
    #[prost(bool, tag = "3")]
    pub supports_sframe: bool,
    /// e.g., \["VP8", "VP9", "H264", "opus"\]
    #[prost(string, repeated, tag = "4")]
    pub supported_codecs: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(int32, tag = "5")]
    pub max_video_width: i32,
    #[prost(int32, tag = "6")]
    pub max_video_height: i32,
    #[prost(int32, tag = "7")]
    pub max_video_fps: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitiateCallResponse {
    #[prost(oneof = "initiate_call_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<initiate_call_response::Result>,
}
/// Nested message and enum types in `InitiateCallResponse`.
pub mod initiate_call_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::InitiateCallSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitiateCallSuccess {
    #[prost(string, tag = "1")]
    pub call_id: ::prost::alloc::string::String,
    #[prost(enumeration = "CallState", tag = "2")]
    pub state: i32,
    #[prost(message, optional, tag = "3")]
    pub created_at: ::core::option::Option<super::common::Timestamp>,
    /// TURN/STUN server configuration
    #[prost(message, repeated, tag = "4")]
    pub ice_servers: ::prost::alloc::vec::Vec<IceServer>,
    /// SFrame key material for E2EE
    #[prost(bytes = "vec", tag = "5")]
    pub sframe_key_material: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "6")]
    pub sframe_key_id: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IceServer {
    #[prost(string, repeated, tag = "1")]
    pub urls: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// TURN username
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    /// TURN credential
    #[prost(string, tag = "3")]
    pub credential: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AcceptCallRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub call_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub capabilities: ::core::option::Option<ClientCapabilities>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AcceptCallResponse {
    #[prost(oneof = "accept_call_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<accept_call_response::Result>,
}
/// Nested message and enum types in `AcceptCallResponse`.
pub mod accept_call_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::AcceptCallSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AcceptCallSuccess {
    #[prost(string, tag = "1")]
    pub call_id: ::prost::alloc::string::String,
    #[prost(enumeration = "CallState", tag = "2")]
    pub state: i32,
    #[prost(message, repeated, tag = "3")]
    pub ice_servers: ::prost::alloc::vec::Vec<IceServer>,
    #[prost(bytes = "vec", tag = "4")]
    pub sframe_key_material: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "5")]
    pub sframe_key_id: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RejectCallRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub call_id: ::prost::alloc::string::String,
    /// Optional rejection reason
    #[prost(string, tag = "3")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RejectCallResponse {
    #[prost(oneof = "reject_call_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<reject_call_response::Result>,
}
/// Nested message and enum types in `RejectCallResponse`.
pub mod reject_call_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::RejectCallSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RejectCallSuccess {
    #[prost(bool, tag = "1")]
    pub rejected: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EndCallRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub call_id: ::prost::alloc::string::String,
    #[prost(enumeration = "CallEndReason", tag = "3")]
    pub reason: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EndCallResponse {
    #[prost(oneof = "end_call_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<end_call_response::Result>,
}
/// Nested message and enum types in `EndCallResponse`.
pub mod end_call_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::EndCallSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct EndCallSuccess {
    #[prost(bool, tag = "1")]
    pub ended: bool,
    #[prost(int32, tag = "2")]
    pub duration_seconds: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LeaveCallRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub call_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LeaveCallResponse {
    #[prost(oneof = "leave_call_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<leave_call_response::Result>,
}
/// Nested message and enum types in `LeaveCallResponse`.
pub mod leave_call_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::LeaveCallSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LeaveCallSuccess {
    #[prost(bool, tag = "1")]
    pub left: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JoinCallRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub call_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub capabilities: ::core::option::Option<ClientCapabilities>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JoinCallResponse {
    #[prost(oneof = "join_call_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<join_call_response::Result>,
}
/// Nested message and enum types in `JoinCallResponse`.
pub mod join_call_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::JoinCallSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JoinCallSuccess {
    #[prost(string, tag = "1")]
    pub call_id: ::prost::alloc::string::String,
    #[prost(enumeration = "CallState", tag = "2")]
    pub state: i32,
    #[prost(message, repeated, tag = "3")]
    pub participants: ::prost::alloc::vec::Vec<CallParticipant>,
    #[prost(message, repeated, tag = "4")]
    pub ice_servers: ::prost::alloc::vec::Vec<IceServer>,
    #[prost(bytes = "vec", tag = "5")]
    pub sframe_key_material: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "6")]
    pub sframe_key_id: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CallParticipant {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub is_muted: bool,
    #[prost(bool, tag = "4")]
    pub has_video: bool,
    #[prost(bool, tag = "5")]
    pub is_screen_sharing: bool,
    #[prost(bool, tag = "6")]
    pub is_speaking: bool,
    #[prost(message, optional, tag = "7")]
    pub joined_at: ::core::option::Option<super::common::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetMuteRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub call_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub muted: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetMuteResponse {
    #[prost(oneof = "set_mute_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<set_mute_response::Result>,
}
/// Nested message and enum types in `SetMuteResponse`.
pub mod set_mute_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::SetMuteSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetMuteSuccess {
    #[prost(bool, tag = "1")]
    pub muted: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetVideoRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub call_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub video_enabled: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetVideoResponse {
    #[prost(oneof = "set_video_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<set_video_response::Result>,
}
/// Nested message and enum types in `SetVideoResponse`.
pub mod set_video_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::SetVideoSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetVideoSuccess {
    #[prost(bool, tag = "1")]
    pub video_enabled: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetScreenShareRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub call_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub screen_share_enabled: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetScreenShareResponse {
    #[prost(oneof = "set_screen_share_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<set_screen_share_response::Result>,
}
/// Nested message and enum types in `SetScreenShareResponse`.
pub mod set_screen_share_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::SetScreenShareSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetScreenShareSuccess {
    #[prost(bool, tag = "1")]
    pub screen_share_enabled: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExchangeIceCandidateRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub call_id: ::prost::alloc::string::String,
    /// Which participant to send to
    #[prost(string, tag = "3")]
    pub target_user_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub candidate: ::core::option::Option<IceCandidate>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IceCandidate {
    /// ICE candidate string
    #[prost(string, tag = "1")]
    pub candidate: ::prost::alloc::string::String,
    /// Media stream identification tag
    #[prost(string, tag = "2")]
    pub sdp_mid: ::prost::alloc::string::String,
    /// Media line index
    #[prost(int32, tag = "3")]
    pub sdp_mline_index: i32,
    #[prost(string, tag = "4")]
    pub username_fragment: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExchangeIceCandidateResponse {
    #[prost(oneof = "exchange_ice_candidate_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<exchange_ice_candidate_response::Result>,
}
/// Nested message and enum types in `ExchangeIceCandidateResponse`.
pub mod exchange_ice_candidate_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::ExchangeIceCandidateSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ExchangeIceCandidateSuccess {
    #[prost(bool, tag = "1")]
    pub sent: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExchangeSdpRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub call_id: ::prost::alloc::string::String,
    /// For 1-on-1, empty for group
    #[prost(string, tag = "3")]
    pub target_user_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub sdp: ::core::option::Option<SdpMessage>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdpMessage {
    #[prost(enumeration = "SdpType", tag = "1")]
    pub r#type: i32,
    /// SDP string
    #[prost(string, tag = "2")]
    pub sdp: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExchangeSdpResponse {
    #[prost(oneof = "exchange_sdp_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<exchange_sdp_response::Result>,
}
/// Nested message and enum types in `ExchangeSdpResponse`.
pub mod exchange_sdp_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::ExchangeSdpSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ExchangeSdpSuccess {
    #[prost(bool, tag = "1")]
    pub sent: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCallStateRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub call_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCallStateResponse {
    #[prost(oneof = "get_call_state_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<get_call_state_response::Result>,
}
/// Nested message and enum types in `GetCallStateResponse`.
pub mod get_call_state_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::GetCallStateSuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCallStateSuccess {
    #[prost(string, tag = "1")]
    pub call_id: ::prost::alloc::string::String,
    #[prost(enumeration = "CallType", tag = "2")]
    pub call_type: i32,
    #[prost(enumeration = "CallState", tag = "3")]
    pub state: i32,
    #[prost(bool, tag = "4")]
    pub is_group_call: bool,
    #[prost(string, tag = "5")]
    pub initiator_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "6")]
    pub participants: ::prost::alloc::vec::Vec<CallParticipant>,
    #[prost(message, optional, tag = "7")]
    pub started_at: ::core::option::Option<super::common::Timestamp>,
    #[prost(int32, tag = "8")]
    pub duration_seconds: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCallHistoryRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub limit: i32,
    /// Pagination cursor
    #[prost(string, tag = "3")]
    pub cursor: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCallHistoryResponse {
    #[prost(oneof = "get_call_history_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<get_call_history_response::Result>,
}
/// Nested message and enum types in `GetCallHistoryResponse`.
pub mod get_call_history_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::GetCallHistorySuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCallHistorySuccess {
    #[prost(message, repeated, tag = "1")]
    pub calls: ::prost::alloc::vec::Vec<CallHistoryEntry>,
    #[prost(string, tag = "2")]
    pub next_cursor: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CallHistoryEntry {
    #[prost(string, tag = "1")]
    pub call_id: ::prost::alloc::string::String,
    #[prost(enumeration = "CallType", tag = "2")]
    pub call_type: i32,
    #[prost(bool, tag = "3")]
    pub is_group_call: bool,
    /// Empty for 1-on-1
    #[prost(string, tag = "4")]
    pub group_id: ::prost::alloc::string::String,
    /// For 1-on-1 calls
    #[prost(string, tag = "5")]
    pub other_user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub other_user_name: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub is_outgoing: bool,
    #[prost(enumeration = "CallEndReason", tag = "8")]
    pub end_reason: i32,
    #[prost(message, optional, tag = "9")]
    pub started_at: ::core::option::Option<super::common::Timestamp>,
    #[prost(int32, tag = "10")]
    pub duration_seconds: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamCallEventsRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub call_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CallEvent {
    #[prost(string, tag = "1")]
    pub call_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub timestamp: ::core::option::Option<super::common::Timestamp>,
    #[prost(oneof = "call_event::Event", tags = "3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13")]
    pub event: ::core::option::Option<call_event::Event>,
}
/// Nested message and enum types in `CallEvent`.
pub mod call_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Event {
        #[prost(message, tag = "3")]
        StateChanged(super::CallStateChanged),
        #[prost(message, tag = "4")]
        ParticipantJoined(super::ParticipantJoined),
        #[prost(message, tag = "5")]
        ParticipantLeft(super::ParticipantLeft),
        #[prost(message, tag = "6")]
        ParticipantMuted(super::ParticipantMuted),
        #[prost(message, tag = "7")]
        ParticipantVideoChanged(super::ParticipantVideoChanged),
        #[prost(message, tag = "8")]
        ParticipantScreenShareChanged(super::ParticipantScreenShareChanged),
        #[prost(message, tag = "9")]
        ParticipantSpeaking(super::ParticipantSpeaking),
        #[prost(message, tag = "10")]
        IceCandidateReceived(super::IceCandidateReceived),
        #[prost(message, tag = "11")]
        SdpReceived(super::SdpReceived),
        #[prost(message, tag = "12")]
        SframeKeyRotated(super::SFrameKeyRotated),
        #[prost(message, tag = "13")]
        QualityChanged(super::CallQualityChanged),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CallStateChanged {
    #[prost(enumeration = "CallState", tag = "1")]
    pub old_state: i32,
    #[prost(enumeration = "CallState", tag = "2")]
    pub new_state: i32,
    /// Only set when ending
    #[prost(enumeration = "CallEndReason", tag = "3")]
    pub end_reason: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParticipantJoined {
    #[prost(message, optional, tag = "1")]
    pub participant: ::core::option::Option<CallParticipant>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParticipantLeft {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParticipantMuted {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub is_muted: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParticipantVideoChanged {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub has_video: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParticipantScreenShareChanged {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub is_screen_sharing: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParticipantSpeaking {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub is_speaking: bool,
    /// 0.0 - 1.0
    #[prost(float, tag = "3")]
    pub audio_level: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IceCandidateReceived {
    #[prost(string, tag = "1")]
    pub from_user_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub candidate: ::core::option::Option<IceCandidate>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SdpReceived {
    #[prost(string, tag = "1")]
    pub from_user_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub sdp: ::core::option::Option<SdpMessage>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SFrameKeyRotated {
    #[prost(string, tag = "1")]
    pub from_user_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub new_key_id: u32,
    #[prost(bytes = "vec", tag = "3")]
    pub encrypted_key_material: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CallQualityChanged {
    #[prost(enumeration = "CallQuality", tag = "1")]
    pub quality: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExchangeSFrameKeyRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub call_id: ::prost::alloc::string::String,
    /// Key material encrypted for each participant
    #[prost(message, repeated, tag = "3")]
    pub key_packages: ::prost::alloc::vec::Vec<ParticipantKeyPackage>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParticipantKeyPackage {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// Encrypted with recipient's public key
    #[prost(bytes = "vec", tag = "2")]
    pub encrypted_key_material: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "3")]
    pub key_id: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExchangeSFrameKeyResponse {
    #[prost(oneof = "exchange_s_frame_key_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<exchange_s_frame_key_response::Result>,
}
/// Nested message and enum types in `ExchangeSFrameKeyResponse`.
pub mod exchange_s_frame_key_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::ExchangeSFrameKeySuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ExchangeSFrameKeySuccess {
    #[prost(bool, tag = "1")]
    pub distributed: bool,
    #[prost(int32, tag = "2")]
    pub participants_count: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RotateSFrameKeyRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub call_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub key_packages: ::prost::alloc::vec::Vec<ParticipantKeyPackage>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RotateSFrameKeyResponse {
    #[prost(oneof = "rotate_s_frame_key_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<rotate_s_frame_key_response::Result>,
}
/// Nested message and enum types in `RotateSFrameKeyResponse`.
pub mod rotate_s_frame_key_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Success(super::RotateSFrameKeySuccess),
        #[prost(message, tag = "2")]
        Error(super::super::common::ErrorResponse),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RotateSFrameKeySuccess {
    #[prost(uint32, tag = "1")]
    pub new_key_id: u32,
    #[prost(bool, tag = "2")]
    pub distributed: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HealthRequest {}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CallType {
    UnknownCallType = 0,
    /// Voice-only call
    Voice = 1,
    /// Video call
    Video = 2,
}
impl CallType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnknownCallType => "UNKNOWN_CALL_TYPE",
            Self::Voice => "VOICE",
            Self::Video => "VIDEO",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_CALL_TYPE" => Some(Self::UnknownCallType),
            "VOICE" => Some(Self::Voice),
            "VIDEO" => Some(Self::Video),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CallState {
    UnknownState = 0,
    /// Call is being set up
    Initiating = 1,
    /// Remote party is being notified
    Ringing = 2,
    /// Call accepted, establishing connection
    Connecting = 3,
    /// Call is active
    Connected = 4,
    /// Call is on hold
    OnHold = 5,
    /// Call has ended
    Ended = 6,
    /// Call failed to connect
    Failed = 7,
}
impl CallState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnknownState => "UNKNOWN_STATE",
            Self::Initiating => "INITIATING",
            Self::Ringing => "RINGING",
            Self::Connecting => "CONNECTING",
            Self::Connected => "CONNECTED",
            Self::OnHold => "ON_HOLD",
            Self::Ended => "ENDED",
            Self::Failed => "FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_STATE" => Some(Self::UnknownState),
            "INITIATING" => Some(Self::Initiating),
            "RINGING" => Some(Self::Ringing),
            "CONNECTING" => Some(Self::Connecting),
            "CONNECTED" => Some(Self::Connected),
            "ON_HOLD" => Some(Self::OnHold),
            "ENDED" => Some(Self::Ended),
            "FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CallEndReason {
    UnknownReason = 0,
    /// Normal call completion
    Completed = 1,
    /// Callee declined
    Declined = 2,
    /// No answer
    Missed = 3,
    /// Callee busy
    Busy = 4,
    /// Network/connection failure
    FailedConnection = 5,
    /// Caller cancelled
    Cancelled = 6,
}
impl CallEndReason {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnknownReason => "UNKNOWN_REASON",
            Self::Completed => "COMPLETED",
            Self::Declined => "DECLINED",
            Self::Missed => "MISSED",
            Self::Busy => "BUSY",
            Self::FailedConnection => "FAILED_CONNECTION",
            Self::Cancelled => "CANCELLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_REASON" => Some(Self::UnknownReason),
            "COMPLETED" => Some(Self::Completed),
            "DECLINED" => Some(Self::Declined),
            "MISSED" => Some(Self::Missed),
            "BUSY" => Some(Self::Busy),
            "FAILED_CONNECTION" => Some(Self::FailedConnection),
            "CANCELLED" => Some(Self::Cancelled),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SdpType {
    UnknownSdpType = 0,
    Offer = 1,
    Answer = 2,
    Pranswer = 3,
    Rollback = 4,
}
impl SdpType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnknownSdpType => "UNKNOWN_SDP_TYPE",
            Self::Offer => "OFFER",
            Self::Answer => "ANSWER",
            Self::Pranswer => "PRANSWER",
            Self::Rollback => "ROLLBACK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_SDP_TYPE" => Some(Self::UnknownSdpType),
            "OFFER" => Some(Self::Offer),
            "ANSWER" => Some(Self::Answer),
            "PRANSWER" => Some(Self::Pranswer),
            "ROLLBACK" => Some(Self::Rollback),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CallQuality {
    UnknownQuality = 0,
    Excellent = 1,
    Good = 2,
    Fair = 3,
    Poor = 4,
}
impl CallQuality {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::UnknownQuality => "UNKNOWN_QUALITY",
            Self::Excellent => "EXCELLENT",
            Self::Good => "GOOD",
            Self::Fair => "FAIR",
            Self::Poor => "POOR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN_QUALITY" => Some(Self::UnknownQuality),
            "EXCELLENT" => Some(Self::Excellent),
            "GOOD" => Some(Self::Good),
            "FAIR" => Some(Self::Fair),
            "POOR" => Some(Self::Poor),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod call_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct CallServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl CallServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> CallServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> CallServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            CallServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Initiate a call (1-on-1 or group)
        pub async fn initiate_call(
            &mut self,
            request: impl tonic::IntoRequest<super::InitiateCallRequest>,
        ) -> std::result::Result<
            tonic::Response<super::InitiateCallResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.calls.CallService/InitiateCall",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.calls.CallService", "InitiateCall"));
            self.inner.unary(req, path, codec).await
        }
        /// Accept an incoming call
        pub async fn accept_call(
            &mut self,
            request: impl tonic::IntoRequest<super::AcceptCallRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AcceptCallResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.calls.CallService/AcceptCall",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.calls.CallService", "AcceptCall"));
            self.inner.unary(req, path, codec).await
        }
        /// Reject an incoming call
        pub async fn reject_call(
            &mut self,
            request: impl tonic::IntoRequest<super::RejectCallRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RejectCallResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.calls.CallService/RejectCall",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.calls.CallService", "RejectCall"));
            self.inner.unary(req, path, codec).await
        }
        /// End an active call
        pub async fn end_call(
            &mut self,
            request: impl tonic::IntoRequest<super::EndCallRequest>,
        ) -> std::result::Result<
            tonic::Response<super::EndCallResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.calls.CallService/EndCall",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.calls.CallService", "EndCall"));
            self.inner.unary(req, path, codec).await
        }
        /// Join an ongoing group call
        pub async fn join_call(
            &mut self,
            request: impl tonic::IntoRequest<super::JoinCallRequest>,
        ) -> std::result::Result<
            tonic::Response<super::JoinCallResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.calls.CallService/JoinCall",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.calls.CallService", "JoinCall"));
            self.inner.unary(req, path, codec).await
        }
        /// Leave a group call (without ending it)
        pub async fn leave_call(
            &mut self,
            request: impl tonic::IntoRequest<super::LeaveCallRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LeaveCallResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.calls.CallService/LeaveCall",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.calls.CallService", "LeaveCall"));
            self.inner.unary(req, path, codec).await
        }
        /// Mute/unmute audio
        pub async fn set_mute(
            &mut self,
            request: impl tonic::IntoRequest<super::SetMuteRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetMuteResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.calls.CallService/SetMute",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.calls.CallService", "SetMute"));
            self.inner.unary(req, path, codec).await
        }
        /// Enable/disable video
        pub async fn set_video(
            &mut self,
            request: impl tonic::IntoRequest<super::SetVideoRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetVideoResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.calls.CallService/SetVideo",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.calls.CallService", "SetVideo"));
            self.inner.unary(req, path, codec).await
        }
        /// Screen sharing
        pub async fn set_screen_share(
            &mut self,
            request: impl tonic::IntoRequest<super::SetScreenShareRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SetScreenShareResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.calls.CallService/SetScreenShare",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.calls.CallService", "SetScreenShare"));
            self.inner.unary(req, path, codec).await
        }
        /// Exchange ICE candidates (WebRTC signaling)
        pub async fn exchange_ice_candidate(
            &mut self,
            request: impl tonic::IntoRequest<super::ExchangeIceCandidateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExchangeIceCandidateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.calls.CallService/ExchangeIceCandidate",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.calls.CallService", "ExchangeIceCandidate"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Exchange SDP offer/answer (WebRTC signaling)
        pub async fn exchange_sdp(
            &mut self,
            request: impl tonic::IntoRequest<super::ExchangeSdpRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExchangeSdpResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.calls.CallService/ExchangeSdp",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.calls.CallService", "ExchangeSdp"));
            self.inner.unary(req, path, codec).await
        }
        /// Get current call state
        pub async fn get_call_state(
            &mut self,
            request: impl tonic::IntoRequest<super::GetCallStateRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetCallStateResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.calls.CallService/GetCallState",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.calls.CallService", "GetCallState"));
            self.inner.unary(req, path, codec).await
        }
        /// Get call history
        pub async fn get_call_history(
            &mut self,
            request: impl tonic::IntoRequest<super::GetCallHistoryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetCallHistoryResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.calls.CallService/GetCallHistory",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.calls.CallService", "GetCallHistory"));
            self.inner.unary(req, path, codec).await
        }
        /// Stream call events (participant joined/left, state changes)
        pub async fn stream_call_events(
            &mut self,
            request: impl tonic::IntoRequest<super::StreamCallEventsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::CallEvent>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.calls.CallService/StreamCallEvents",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.calls.CallService", "StreamCallEvents"),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Exchange SFrame encryption keys
        pub async fn exchange_s_frame_key(
            &mut self,
            request: impl tonic::IntoRequest<super::ExchangeSFrameKeyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ExchangeSFrameKeyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.calls.CallService/ExchangeSFrameKey",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("guardyn.calls.CallService", "ExchangeSFrameKey"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Rotate SFrame encryption key
        pub async fn rotate_s_frame_key(
            &mut self,
            request: impl tonic::IntoRequest<super::RotateSFrameKeyRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RotateSFrameKeyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.calls.CallService/RotateSFrameKey",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.calls.CallService", "RotateSFrameKey"));
            self.inner.unary(req, path, codec).await
        }
        /// Health check
        pub async fn health(
            &mut self,
            request: impl tonic::IntoRequest<super::HealthRequest>,
        ) -> std::result::Result<
            tonic::Response<super::super::common::HealthStatus>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/guardyn.calls.CallService/Health",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("guardyn.calls.CallService", "Health"));
            self.inner.unary(req, path, codec).await
        }
    }
}
