//! Generated Protocol Buffer modules
//!
//! These modules are generated by tonic-build from .proto files.
//! Do not edit manually - changes will be overwritten on rebuild.

// Common types
pub mod guardyn {
    pub mod common {
        include!("guardyn.common.rs");
    }

    pub mod auth {
        include!("guardyn.auth.rs");
    }

    pub mod messaging {
        include!("guardyn.messaging.rs");
    }

    pub mod presence {
        include!("guardyn.presence.rs");
    }

    pub mod media {
        include!("guardyn.media.rs");
    }

    pub mod calls {
        include!("guardyn.calls.rs");
    }

    pub mod notifications {
        include!("guardyn.notifications.rs");
    }
}

// Re-exports for convenience
pub use guardyn::auth;
pub use guardyn::calls;
pub use guardyn::common;
pub use guardyn::media;
pub use guardyn::messaging;
pub use guardyn::notifications;
pub use guardyn::presence;
