// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = DcoCodec,
    default_rust_opaque = RustOpaqueNom,
    default_rust_auto_opaque = RustAutoOpaqueNom,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -694979162;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__crypto_constant_time_eq_impl(
    a: impl CstDecode<Vec<u8>>,
    b: impl CstDecode<Vec<u8>>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "crypto_constant_time_eq",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_a = a.cst_decode();
            let api_b = b.cst_decode();
            transform_result_dco::<_, _, ()>((move || {
                let output_ok =
                    Result::<_, ()>::Ok(crate::api::crypto_constant_time_eq(api_a, api_b))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__crypto_decrypt_aes_gcm_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    encrypted: impl CstDecode<crate::api::EncryptedData>,
    key: impl CstDecode<Vec<u8>>,
    associated_data: impl CstDecode<Option<Vec<u8>>>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "crypto_decrypt_aes_gcm",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_encrypted = encrypted.cst_decode();
            let api_key = key.cst_decode();
            let api_associated_data = associated_data.cst_decode();
            move |context| {
                transform_result_dco::<_, _, String>((move || {
                    let output_ok = crate::api::crypto_decrypt_aes_gcm(
                        api_encrypted,
                        api_key,
                        api_associated_data,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__crypto_decrypt_chacha20_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    encrypted: impl CstDecode<crate::api::EncryptedData>,
    key: impl CstDecode<Vec<u8>>,
    associated_data: impl CstDecode<Option<Vec<u8>>>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "crypto_decrypt_chacha20",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_encrypted = encrypted.cst_decode();
            let api_key = key.cst_decode();
            let api_associated_data = associated_data.cst_decode();
            move |context| {
                transform_result_dco::<_, _, String>((move || {
                    let output_ok = crate::api::crypto_decrypt_chacha20(
                        api_encrypted,
                        api_key,
                        api_associated_data,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__crypto_ed25519_public_to_x25519_impl(
    ed25519_public: impl CstDecode<Vec<u8>>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "crypto_ed25519_public_to_x25519",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_ed25519_public = ed25519_public.cst_decode();
            transform_result_dco::<_, _, String>((move || {
                let output_ok = crate::api::crypto_ed25519_public_to_x25519(api_ed25519_public)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__crypto_ed25519_secret_to_x25519_impl(
    ed25519_seed: impl CstDecode<Vec<u8>>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "crypto_ed25519_secret_to_x25519",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_ed25519_seed = ed25519_seed.cst_decode();
            transform_result_dco::<_, _, String>((move || {
                let output_ok = crate::api::crypto_ed25519_secret_to_x25519(api_ed25519_seed)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__crypto_encrypt_aes_gcm_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    plaintext: impl CstDecode<Vec<u8>>,
    key: impl CstDecode<Vec<u8>>,
    nonce: impl CstDecode<Option<Vec<u8>>>,
    associated_data: impl CstDecode<Option<Vec<u8>>>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "crypto_encrypt_aes_gcm",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_plaintext = plaintext.cst_decode();
            let api_key = key.cst_decode();
            let api_nonce = nonce.cst_decode();
            let api_associated_data = associated_data.cst_decode();
            move |context| {
                transform_result_dco::<_, _, String>((move || {
                    let output_ok = crate::api::crypto_encrypt_aes_gcm(
                        api_plaintext,
                        api_key,
                        api_nonce,
                        api_associated_data,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__crypto_encrypt_chacha20_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    plaintext: impl CstDecode<Vec<u8>>,
    key: impl CstDecode<Vec<u8>>,
    nonce: impl CstDecode<Option<Vec<u8>>>,
    associated_data: impl CstDecode<Option<Vec<u8>>>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "crypto_encrypt_chacha20",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_plaintext = plaintext.cst_decode();
            let api_key = key.cst_decode();
            let api_nonce = nonce.cst_decode();
            let api_associated_data = associated_data.cst_decode();
            move |context| {
                transform_result_dco::<_, _, String>((move || {
                    let output_ok = crate::api::crypto_encrypt_chacha20(
                        api_plaintext,
                        api_key,
                        api_nonce,
                        api_associated_data,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__crypto_generate_ed25519_keypair_impl(
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "crypto_generate_ed25519_keypair",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            transform_result_dco::<_, _, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::crypto_generate_ed25519_keypair())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__crypto_generate_hybrid_key_bundle_impl(
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "crypto_generate_hybrid_key_bundle",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            transform_result_dco::<_, _, String>((move || {
                let output_ok = crate::api::crypto_generate_hybrid_key_bundle()?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__crypto_generate_x25519_keypair_impl(
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "crypto_generate_x25519_keypair",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            transform_result_dco::<_, _, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::crypto_generate_x25519_keypair())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__crypto_hkdf_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    input_key_material: impl CstDecode<Vec<u8>>,
    salt: impl CstDecode<Option<Vec<u8>>>,
    info: impl CstDecode<Vec<u8>>,
    output_length: impl CstDecode<u32>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "crypto_hkdf",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_input_key_material = input_key_material.cst_decode();
            let api_salt = salt.cst_decode();
            let api_info = info.cst_decode();
            let api_output_length = output_length.cst_decode();
            move |context| {
                transform_result_dco::<_, _, String>((move || {
                    let output_ok = crate::api::crypto_hkdf(
                        api_input_key_material,
                        api_salt,
                        api_info,
                        api_output_length,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__crypto_init_impl() -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco
{
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "crypto_init",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            transform_result_dco::<_, _, String>((move || {
                let output_ok = crate::api::crypto_init()?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__crypto_is_pq_available_impl(
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "crypto_is_pq_available",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            transform_result_dco::<_, _, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::crypto_is_pq_available())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__crypto_pad_message_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    message: impl CstDecode<Vec<u8>>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "crypto_pad_message",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_message = message.cst_decode();
            move |context| {
                transform_result_dco::<_, _, String>((move || {
                    let output_ok = crate::api::crypto_pad_message(api_message)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__crypto_random_bytes_impl(
    length: impl CstDecode<u32>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "crypto_random_bytes",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_length = length.cst_decode();
            transform_result_dco::<_, _, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::crypto_random_bytes(api_length))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__crypto_sign_ed25519_impl(
    private_key: impl CstDecode<Vec<u8>>,
    message: impl CstDecode<Vec<u8>>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "crypto_sign_ed25519",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_private_key = private_key.cst_decode();
            let api_message = message.cst_decode();
            transform_result_dco::<_, _, String>((move || {
                let output_ok = crate::api::crypto_sign_ed25519(api_private_key, api_message)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__crypto_status_impl() -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco
{
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "crypto_status",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            transform_result_dco::<_, _, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::crypto_status())?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__crypto_unpad_message_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    padded_message: impl CstDecode<Vec<u8>>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "crypto_unpad_message",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_padded_message = padded_message.cst_decode();
            move |context| {
                transform_result_dco::<_, _, String>((move || {
                    let output_ok = crate::api::crypto_unpad_message(api_padded_message)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__crypto_verify_ed25519_impl(
    public_key: impl CstDecode<Vec<u8>>,
    message: impl CstDecode<Vec<u8>>,
    signature: impl CstDecode<Vec<u8>>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "crypto_verify_ed25519",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_public_key = public_key.cst_decode();
            let api_message = message.cst_decode();
            let api_signature = signature.cst_decode();
            transform_result_dco::<_, _, String>((move || {
                let output_ok =
                    crate::api::crypto_verify_ed25519(api_public_key, api_message, api_signature)?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__crypto_x25519_dh_impl(
    private_key: impl CstDecode<Vec<u8>>,
    public_key: impl CstDecode<Vec<u8>>,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::DcoCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "crypto_x25519_dh",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let api_private_key = private_key.cst_decode();
            let api_public_key = public_key.cst_decode();
            transform_result_dco::<_, _, String>((move || {
                let output_ok = crate::api::crypto_x25519_dh(api_private_key, api_public_key)?;
                Ok(output_ok)
            })())
        },
    )
}

// Section: dart2rust

impl CstDecode<bool> for bool {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> bool {
        self
    }
}
impl CstDecode<u32> for u32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u32 {
        self
    }
}
impl CstDecode<u8> for u8 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u8 {
        self
    }
}
impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::CryptoStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_initialized = <bool>::sse_decode(deserializer);
        let mut var_postQuantumAvailable = <bool>::sse_decode(deserializer);
        let mut var_version = <String>::sse_decode(deserializer);
        return crate::api::CryptoStatus {
            initialized: var_initialized,
            post_quantum_available: var_postQuantumAvailable,
            version: var_version,
        };
    }
}

impl SseDecode for crate::api::EncryptedData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_ciphertext = <Vec<u8>>::sse_decode(deserializer);
        let mut var_nonce = <Vec<u8>>::sse_decode(deserializer);
        let mut var_tag = <Vec<u8>>::sse_decode(deserializer);
        return crate::api::EncryptedData {
            ciphertext: var_ciphertext,
            nonce: var_nonce,
            tag: var_tag,
        };
    }
}

impl SseDecode for crate::api::HybridKeyBundle {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_x25519Public = <Vec<u8>>::sse_decode(deserializer);
        let mut var_x25519Private = <Vec<u8>>::sse_decode(deserializer);
        let mut var_mlKemPublic = <Vec<u8>>::sse_decode(deserializer);
        let mut var_mlKemPrivate = <Vec<u8>>::sse_decode(deserializer);
        return crate::api::HybridKeyBundle {
            x25519_public: var_x25519Public,
            x25519_private: var_x25519Private,
            ml_kem_public: var_mlKemPublic,
            ml_kem_private: var_mlKemPrivate,
        };
    }
}

impl SseDecode for crate::api::KeyPair {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_publicKey = <Vec<u8>>::sse_decode(deserializer);
        let mut var_privateKey = <Vec<u8>>::sse_decode(deserializer);
        let mut var_keyType = <String>::sse_decode(deserializer);
        return crate::api::KeyPair {
            public_key: var_publicKey,
            private_key: var_privateKey,
            key_type: var_keyType,
        };
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<crate::api::HybridKeyBundle> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::HybridKeyBundle>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<Vec<u8>>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::CryptoStatus {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.initialized.into_into_dart().into_dart(),
            self.post_quantum_available.into_into_dart().into_dart(),
            self.version.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::CryptoStatus {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::CryptoStatus> for crate::api::CryptoStatus {
    fn into_into_dart(self) -> crate::api::CryptoStatus {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::EncryptedData {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.ciphertext.into_into_dart().into_dart(),
            self.nonce.into_into_dart().into_dart(),
            self.tag.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::EncryptedData {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::EncryptedData> for crate::api::EncryptedData {
    fn into_into_dart(self) -> crate::api::EncryptedData {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::HybridKeyBundle {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.x25519_public.into_into_dart().into_dart(),
            self.x25519_private.into_into_dart().into_dart(),
            self.ml_kem_public.into_into_dart().into_dart(),
            self.ml_kem_private.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::HybridKeyBundle {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::HybridKeyBundle>
    for crate::api::HybridKeyBundle
{
    fn into_into_dart(self) -> crate::api::HybridKeyBundle {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::KeyPair {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.public_key.into_into_dart().into_dart(),
            self.private_key.into_into_dart().into_dart(),
            self.key_type.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::KeyPair {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::KeyPair> for crate::api::KeyPair {
    fn into_into_dart(self) -> crate::api::KeyPair {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::CryptoStatus {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.initialized, serializer);
        <bool>::sse_encode(self.post_quantum_available, serializer);
        <String>::sse_encode(self.version, serializer);
    }
}

impl SseEncode for crate::api::EncryptedData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.ciphertext, serializer);
        <Vec<u8>>::sse_encode(self.nonce, serializer);
        <Vec<u8>>::sse_encode(self.tag, serializer);
    }
}

impl SseEncode for crate::api::HybridKeyBundle {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.x25519_public, serializer);
        <Vec<u8>>::sse_encode(self.x25519_private, serializer);
        <Vec<u8>>::sse_encode(self.ml_kem_public, serializer);
        <Vec<u8>>::sse_encode(self.ml_kem_private, serializer);
    }
}

impl SseEncode for crate::api::KeyPair {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.public_key, serializer);
        <Vec<u8>>::sse_encode(self.private_key, serializer);
        <String>::sse_encode(self.key_type, serializer);
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::HybridKeyBundle> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::HybridKeyBundle>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<Vec<u8>> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <Vec<u8>>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();

    // Section: dart2rust

    impl CstDecode<String> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            let vec: Vec<u8> = self.cst_decode();
            String::from_utf8(vec).unwrap()
        }
    }
    impl CstDecode<crate::api::EncryptedData> for *mut wire_cst_encrypted_data {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::EncryptedData {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<crate::api::EncryptedData>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<crate::api::HybridKeyBundle> for *mut wire_cst_hybrid_key_bundle {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::HybridKeyBundle {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<crate::api::HybridKeyBundle>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<crate::api::CryptoStatus> for wire_cst_crypto_status {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::CryptoStatus {
            crate::api::CryptoStatus {
                initialized: self.initialized.cst_decode(),
                post_quantum_available: self.post_quantum_available.cst_decode(),
                version: self.version.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::EncryptedData> for wire_cst_encrypted_data {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::EncryptedData {
            crate::api::EncryptedData {
                ciphertext: self.ciphertext.cst_decode(),
                nonce: self.nonce.cst_decode(),
                tag: self.tag.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::HybridKeyBundle> for wire_cst_hybrid_key_bundle {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::HybridKeyBundle {
            crate::api::HybridKeyBundle {
                x25519_public: self.x25519_public.cst_decode(),
                x25519_private: self.x25519_private.cst_decode(),
                ml_kem_public: self.ml_kem_public.cst_decode(),
                ml_kem_private: self.ml_kem_private.cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::KeyPair> for wire_cst_key_pair {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::KeyPair {
            crate::api::KeyPair {
                public_key: self.public_key.cst_decode(),
                private_key: self.private_key.cst_decode(),
                key_type: self.key_type.cst_decode(),
            }
        }
    }
    impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_loose {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    impl NewWithNullPtr for wire_cst_crypto_status {
        fn new_with_null_ptr() -> Self {
            Self {
                initialized: Default::default(),
                post_quantum_available: Default::default(),
                version: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_crypto_status {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_encrypted_data {
        fn new_with_null_ptr() -> Self {
            Self {
                ciphertext: core::ptr::null_mut(),
                nonce: core::ptr::null_mut(),
                tag: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_encrypted_data {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_hybrid_key_bundle {
        fn new_with_null_ptr() -> Self {
            Self {
                x25519_public: core::ptr::null_mut(),
                x25519_private: core::ptr::null_mut(),
                ml_kem_public: core::ptr::null_mut(),
                ml_kem_private: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_hybrid_key_bundle {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_key_pair {
        fn new_with_null_ptr() -> Self {
            Self {
                public_key: core::ptr::null_mut(),
                private_key: core::ptr::null_mut(),
                key_type: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_key_pair {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_wire__crate__api__crypto_constant_time_eq(
        a: *mut wire_cst_list_prim_u_8_loose,
        b: *mut wire_cst_list_prim_u_8_loose,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_constant_time_eq_impl(a, b)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_wire__crate__api__crypto_decrypt_aes_gcm(
        port_: i64,
        encrypted: *mut wire_cst_encrypted_data,
        key: *mut wire_cst_list_prim_u_8_loose,
        associated_data: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__crypto_decrypt_aes_gcm_impl(port_, encrypted, key, associated_data)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_wire__crate__api__crypto_decrypt_chacha20(
        port_: i64,
        encrypted: *mut wire_cst_encrypted_data,
        key: *mut wire_cst_list_prim_u_8_loose,
        associated_data: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__crypto_decrypt_chacha20_impl(port_, encrypted, key, associated_data)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_wire__crate__api__crypto_ed25519_public_to_x25519(
        ed25519_public: *mut wire_cst_list_prim_u_8_loose,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_ed25519_public_to_x25519_impl(ed25519_public)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_wire__crate__api__crypto_ed25519_secret_to_x25519(
        ed25519_seed: *mut wire_cst_list_prim_u_8_loose,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_ed25519_secret_to_x25519_impl(ed25519_seed)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_wire__crate__api__crypto_encrypt_aes_gcm(
        port_: i64,
        plaintext: *mut wire_cst_list_prim_u_8_loose,
        key: *mut wire_cst_list_prim_u_8_loose,
        nonce: *mut wire_cst_list_prim_u_8_strict,
        associated_data: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__crypto_encrypt_aes_gcm_impl(port_, plaintext, key, nonce, associated_data)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_wire__crate__api__crypto_encrypt_chacha20(
        port_: i64,
        plaintext: *mut wire_cst_list_prim_u_8_loose,
        key: *mut wire_cst_list_prim_u_8_loose,
        nonce: *mut wire_cst_list_prim_u_8_strict,
        associated_data: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__crate__api__crypto_encrypt_chacha20_impl(
            port_,
            plaintext,
            key,
            nonce,
            associated_data,
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_wire__crate__api__crypto_generate_ed25519_keypair(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_generate_ed25519_keypair_impl()
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_wire__crate__api__crypto_generate_hybrid_key_bundle(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_generate_hybrid_key_bundle_impl()
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_wire__crate__api__crypto_generate_x25519_keypair(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_generate_x25519_keypair_impl()
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_wire__crate__api__crypto_hkdf(
        port_: i64,
        input_key_material: *mut wire_cst_list_prim_u_8_loose,
        salt: *mut wire_cst_list_prim_u_8_strict,
        info: *mut wire_cst_list_prim_u_8_loose,
        output_length: u32,
    ) {
        wire__crate__api__crypto_hkdf_impl(port_, input_key_material, salt, info, output_length)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_wire__crate__api__crypto_init(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_init_impl()
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_wire__crate__api__crypto_is_pq_available(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_is_pq_available_impl()
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_wire__crate__api__crypto_pad_message(
        port_: i64,
        message: *mut wire_cst_list_prim_u_8_loose,
    ) {
        wire__crate__api__crypto_pad_message_impl(port_, message)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_wire__crate__api__crypto_random_bytes(
        length: u32,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_random_bytes_impl(length)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_wire__crate__api__crypto_sign_ed25519(
        private_key: *mut wire_cst_list_prim_u_8_loose,
        message: *mut wire_cst_list_prim_u_8_loose,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_sign_ed25519_impl(private_key, message)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_wire__crate__api__crypto_status(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_status_impl()
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_wire__crate__api__crypto_unpad_message(
        port_: i64,
        padded_message: *mut wire_cst_list_prim_u_8_loose,
    ) {
        wire__crate__api__crypto_unpad_message_impl(port_, padded_message)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_wire__crate__api__crypto_verify_ed25519(
        public_key: *mut wire_cst_list_prim_u_8_loose,
        message: *mut wire_cst_list_prim_u_8_loose,
        signature: *mut wire_cst_list_prim_u_8_loose,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_verify_ed25519_impl(public_key, message, signature)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_wire__crate__api__crypto_x25519_dh(
        private_key: *mut wire_cst_list_prim_u_8_loose,
        public_key: *mut wire_cst_list_prim_u_8_loose,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_x25519_dh_impl(private_key, public_key)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_cst_new_box_autoadd_encrypted_data(
    ) -> *mut wire_cst_encrypted_data {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(
            wire_cst_encrypted_data::new_with_null_ptr(),
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_cst_new_box_autoadd_hybrid_key_bundle(
    ) -> *mut wire_cst_hybrid_key_bundle {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(
            wire_cst_hybrid_key_bundle::new_with_null_ptr(),
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_cst_new_list_prim_u_8_loose(
        len: i32,
    ) -> *mut wire_cst_list_prim_u_8_loose {
        let ans = wire_cst_list_prim_u_8_loose {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_guardyn_client_cst_new_list_prim_u_8_strict(
        len: i32,
    ) -> *mut wire_cst_list_prim_u_8_strict {
        let ans = wire_cst_list_prim_u_8_strict {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
    }

    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_crypto_status {
        initialized: bool,
        post_quantum_available: bool,
        version: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_encrypted_data {
        ciphertext: *mut wire_cst_list_prim_u_8_strict,
        nonce: *mut wire_cst_list_prim_u_8_strict,
        tag: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_hybrid_key_bundle {
        x25519_public: *mut wire_cst_list_prim_u_8_strict,
        x25519_private: *mut wire_cst_list_prim_u_8_strict,
        ml_kem_public: *mut wire_cst_list_prim_u_8_strict,
        ml_kem_private: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_key_pair {
        public_key: *mut wire_cst_list_prim_u_8_strict,
        private_key: *mut wire_cst_list_prim_u_8_strict,
        key_type: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_prim_u_8_loose {
        ptr: *mut u8,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_prim_u_8_strict {
        ptr: *mut u8,
        len: i32,
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();

    // Section: dart2rust

    impl CstDecode<String> for String {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            self
        }
    }
    impl CstDecode<crate::api::CryptoStatus>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::CryptoStatus {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                3,
                "Expected 3 elements, got {}",
                self_.length()
            );
            crate::api::CryptoStatus {
                initialized: self_.get(0).cst_decode(),
                post_quantum_available: self_.get(1).cst_decode(),
                version: self_.get(2).cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::EncryptedData>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::EncryptedData {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                3,
                "Expected 3 elements, got {}",
                self_.length()
            );
            crate::api::EncryptedData {
                ciphertext: self_.get(0).cst_decode(),
                nonce: self_.get(1).cst_decode(),
                tag: self_.get(2).cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::HybridKeyBundle>
        for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::HybridKeyBundle {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                4,
                "Expected 4 elements, got {}",
                self_.length()
            );
            crate::api::HybridKeyBundle {
                x25519_public: self_.get(0).cst_decode(),
                x25519_private: self_.get(1).cst_decode(),
                ml_kem_public: self_.get(2).cst_decode(),
                ml_kem_private: self_.get(3).cst_decode(),
            }
        }
    }
    impl CstDecode<crate::api::KeyPair> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> crate::api::KeyPair {
            let self_ = self
                .dyn_into::<flutter_rust_bridge::for_generated::js_sys::Array>()
                .unwrap();
            assert_eq!(
                self_.length(),
                3,
                "Expected 3 elements, got {}",
                self_.length()
            );
            crate::api::KeyPair {
                public_key: self_.get(0).cst_decode(),
                private_key: self_.get(1).cst_decode(),
                key_type: self_.get(2).cst_decode(),
            }
        }
    }
    impl CstDecode<Vec<u8>> for Box<[u8]> {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            self.into_vec()
        }
    }
    impl CstDecode<Option<Vec<u8>>> for Option<Box<[u8]>> {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Option<Vec<u8>> {
            self.map(CstDecode::cst_decode)
        }
    }
    impl CstDecode<String> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            self.as_string().expect("non-UTF-8 string, or not a string")
        }
    }
    impl CstDecode<bool> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> bool {
            self.is_truthy()
        }
    }
    impl CstDecode<Vec<u8>> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            self.unchecked_into::<flutter_rust_bridge::for_generated::js_sys::Uint8Array>()
                .to_vec()
                .into()
        }
    }
    impl CstDecode<u32> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u32 {
            self.unchecked_into_f64() as _
        }
    }
    impl CstDecode<u8> for flutter_rust_bridge::for_generated::wasm_bindgen::JsValue {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> u8 {
            self.unchecked_into_f64() as _
        }
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__crypto_constant_time_eq(
        a: Box<[u8]>,
        b: Box<[u8]>,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_constant_time_eq_impl(a, b)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__crypto_decrypt_aes_gcm(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        encrypted: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
        key: Box<[u8]>,
        associated_data: Option<Box<[u8]>>,
    ) {
        wire__crate__api__crypto_decrypt_aes_gcm_impl(port_, encrypted, key, associated_data)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__crypto_decrypt_chacha20(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        encrypted: flutter_rust_bridge::for_generated::wasm_bindgen::JsValue,
        key: Box<[u8]>,
        associated_data: Option<Box<[u8]>>,
    ) {
        wire__crate__api__crypto_decrypt_chacha20_impl(port_, encrypted, key, associated_data)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__crypto_ed25519_public_to_x25519(
        ed25519_public: Box<[u8]>,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_ed25519_public_to_x25519_impl(ed25519_public)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__crypto_ed25519_secret_to_x25519(
        ed25519_seed: Box<[u8]>,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_ed25519_secret_to_x25519_impl(ed25519_seed)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__crypto_encrypt_aes_gcm(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        plaintext: Box<[u8]>,
        key: Box<[u8]>,
        nonce: Option<Box<[u8]>>,
        associated_data: Option<Box<[u8]>>,
    ) {
        wire__crate__api__crypto_encrypt_aes_gcm_impl(port_, plaintext, key, nonce, associated_data)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__crypto_encrypt_chacha20(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        plaintext: Box<[u8]>,
        key: Box<[u8]>,
        nonce: Option<Box<[u8]>>,
        associated_data: Option<Box<[u8]>>,
    ) {
        wire__crate__api__crypto_encrypt_chacha20_impl(
            port_,
            plaintext,
            key,
            nonce,
            associated_data,
        )
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__crypto_generate_ed25519_keypair(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_generate_ed25519_keypair_impl()
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__crypto_generate_hybrid_key_bundle(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_generate_hybrid_key_bundle_impl()
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__crypto_generate_x25519_keypair(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_generate_x25519_keypair_impl()
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__crypto_hkdf(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        input_key_material: Box<[u8]>,
        salt: Option<Box<[u8]>>,
        info: Box<[u8]>,
        output_length: u32,
    ) {
        wire__crate__api__crypto_hkdf_impl(port_, input_key_material, salt, info, output_length)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__crypto_init(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_init_impl()
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__crypto_is_pq_available(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_is_pq_available_impl()
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__crypto_pad_message(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        message: Box<[u8]>,
    ) {
        wire__crate__api__crypto_pad_message_impl(port_, message)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__crypto_random_bytes(
        length: u32,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_random_bytes_impl(length)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__crypto_sign_ed25519(
        private_key: Box<[u8]>,
        message: Box<[u8]>,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_sign_ed25519_impl(private_key, message)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__crypto_status(
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_status_impl()
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__crypto_unpad_message(
        port_: flutter_rust_bridge::for_generated::MessagePort,
        padded_message: Box<[u8]>,
    ) {
        wire__crate__api__crypto_unpad_message_impl(port_, padded_message)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__crypto_verify_ed25519(
        public_key: Box<[u8]>,
        message: Box<[u8]>,
        signature: Box<[u8]>,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_verify_ed25519_impl(public_key, message, signature)
    }

    #[wasm_bindgen]
    pub fn wire__crate__api__crypto_x25519_dh(
        private_key: Box<[u8]>,
        public_key: Box<[u8]>,
    ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartDco {
        wire__crate__api__crypto_x25519_dh_impl(private_key, public_key)
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;
