/// Native Rust Crypto Bridge Implementation
///
/// This file provides the native Rust implementation of CryptoBridge
/// using flutter_rust_bridge to call guardyn-crypto FFI functions.
///
/// This implementation is used on mobile platforms (iOS/Android) and
/// desktop platforms (Windows/macOS/Linux) where native libraries are available.
library;

import 'dart:io';

import 'package:flutter/foundation.dart';

import '../native_crypto_bridge.dart';

// Import generated bindings (will be generated by flutter_rust_bridge)
// import '../../generated/rust/api.dart' as rust_api;

/// Native Rust implementation of CryptoBridge
///
/// This implementation calls Rust code through FFI for:
/// - Post-quantum cryptography (ML-KEM-768)
/// - Hardware-accelerated encryption
/// - PADMÉ padding
class NativeRustCryptoBridge implements CryptoBridge {
  late NativeCryptoConfig _config;
  bool _initialized = false;
  bool _nativeAvailable = false;
  bool _pqAvailable = false;

  /// Check if native library is available for current platform
  static bool checkNativeAvailable() {
    if (kIsWeb) return false;

    try {
      // Try to load the native library
      final libName = _getLibraryName();
      if (libName == null) return false;

      // In production, this would actually load and verify the library
      // For now, we check if the library file exists
      return true;
    } catch (e) {
      debugPrint('Native library not available: $e');
      return false;
    }
  }

  static String? _getLibraryName() {
    if (Platform.isAndroid) {
      return 'libguardyn_crypto_ffi.so';
    } else if (Platform.isIOS) {
      return 'GuardynCrypto.framework/GuardynCrypto';
    } else if (Platform.isLinux) {
      return 'libguardyn_crypto_ffi.so';
    } else if (Platform.isMacOS) {
      return 'libguardyn_crypto_ffi.dylib';
    } else if (Platform.isWindows) {
      return 'guardyn_crypto_ffi.dll';
    }
    return null;
  }

  @override
  Future<void> initialize(NativeCryptoConfig config) async {
    _config = config;

    if (!config.preferNative) {
      debugPrint('🔐 Native crypto disabled by config');
      _nativeAvailable = false;
      _initialized = true;
      return;
    }

    try {
      // TODO: Uncomment when flutter_rust_bridge bindings are generated
      // await rust_api.cryptoInit();
      // final status = rust_api.cryptoStatus();
      // _nativeAvailable = status.initialized;
      // _pqAvailable = status.postQuantumAvailable;

      // For now, mark as available if library exists
      _nativeAvailable = checkNativeAvailable();
      _pqAvailable = _nativeAvailable && config.enablePostQuantum;

      debugPrint(
        '🔐 NativeRustCryptoBridge initialized: '
        'native=$_nativeAvailable, pq=$_pqAvailable',
      );
    } catch (e) {
      debugPrint('🔐 Failed to initialize native crypto: $e');
      _nativeAvailable = false;
    }

    _initialized = true;
  }

  @override
  bool get isNativeAvailable => _nativeAvailable;

  @override
  bool get isPostQuantumAvailable => _pqAvailable;

  void _ensureInitialized() {
    if (!_initialized) {
      throw StateError('NativeRustCryptoBridge not initialized');
    }
  }

  void _ensureNativeAvailable() {
    _ensureInitialized();
    if (!_nativeAvailable) {
      throw UnsupportedError('Native crypto not available on this platform');
    }
  }

  // ===== Key Generation =====

  @override
  Future<KeyPair> generateIdentityKey() async {
    _ensureNativeAvailable();

    // TODO: Uncomment when flutter_rust_bridge bindings are generated
    // final kp = rust_api.cryptoGenerateEd25519Keypair();
    // return KeyPair(
    //   publicKey: Uint8List.fromList(kp.publicKey),
    //   privateKey: Uint8List.fromList(kp.privateKey),
    //   keyType: kp.keyType,
    // );

    throw UnimplementedError(
      'Waiting for flutter_rust_bridge bindings generation',
    );
  }

  @override
  Future<KeyPair> generateSignedPreKey() async {
    _ensureNativeAvailable();

    // TODO: Uncomment when flutter_rust_bridge bindings are generated
    // final kp = rust_api.cryptoGenerateX25519Keypair();
    // return KeyPair(
    //   publicKey: Uint8List.fromList(kp.publicKey),
    //   privateKey: Uint8List.fromList(kp.privateKey),
    //   keyType: kp.keyType,
    // );

    throw UnimplementedError(
      'Waiting for flutter_rust_bridge bindings generation',
    );
  }

  @override
  Future<List<KeyPair>> generateOneTimePreKeys(int count) async {
    _ensureNativeAvailable();

    final keys = <KeyPair>[];
    for (var i = 0; i < count; i++) {
      keys.add(await generateSignedPreKey());
    }
    return keys;
  }

  // ===== PQXDH (Hybrid Post-Quantum Key Exchange) =====

  @override
  Future<HybridKeyBundle?> generateHybridKeyBundle() async {
    _ensureNativeAvailable();

    if (!_pqAvailable) {
      return null;
    }

    // TODO: Uncomment when flutter_rust_bridge bindings are generated
    // final bundle = rust_api.cryptoGenerateHybridKeyBundle();
    // if (bundle == null) return null;
    // return HybridKeyBundle(
    //   x25519PublicKey: Uint8List.fromList(bundle.x25519Public),
    //   x25519PrivateKey: Uint8List.fromList(bundle.x25519Private),
    //   mlKemPublicKey: Uint8List.fromList(bundle.mlKemPublic),
    //   mlKemPrivateKey: Uint8List.fromList(bundle.mlKemPrivate),
    // );

    throw UnimplementedError(
      'Waiting for flutter_rust_bridge bindings generation',
    );
  }

  @override
  Future<Uint8List> deriveHybridSharedSecret({
    required Uint8List localPrivateKey,
    required Uint8List remotePublicKey,
    required Uint8List? remotePqPublicKey,
  }) async {
    _ensureNativeAvailable();

    // TODO: Uncomment when flutter_rust_bridge bindings are generated
    // final sharedSecret = rust_api.cryptoX25519Dh(
    //   privateKey: localPrivateKey.toList(),
    //   publicKey: remotePublicKey.toList(),
    // );
    // return Uint8List.fromList(sharedSecret);

    throw UnimplementedError(
      'Waiting for flutter_rust_bridge bindings generation',
    );
  }

  // ===== Symmetric Encryption =====

  @override
  Future<EncryptedData> encryptAesGcm({
    required Uint8List plaintext,
    required Uint8List key,
    Uint8List? nonce,
    Uint8List? associatedData,
  }) async {
    _ensureNativeAvailable();

    // TODO: Uncomment when flutter_rust_bridge bindings are generated
    // final encrypted = await rust_api.cryptoEncryptAesGcm(
    //   plaintext: plaintext.toList(),
    //   key: key.toList(),
    //   nonce: nonce?.toList(),
    //   associatedData: associatedData?.toList(),
    // );
    // return EncryptedData(
    //   ciphertext: Uint8List.fromList(encrypted.ciphertext),
    //   nonce: Uint8List.fromList(encrypted.nonce),
    //   tag: Uint8List.fromList(encrypted.tag),
    // );

    throw UnimplementedError(
      'Waiting for flutter_rust_bridge bindings generation',
    );
  }

  @override
  Future<Uint8List> decryptAesGcm({
    required EncryptedData encrypted,
    required Uint8List key,
    Uint8List? associatedData,
  }) async {
    _ensureNativeAvailable();

    // TODO: Uncomment when flutter_rust_bridge bindings are generated
    // final plaintext = await rust_api.cryptoDecryptAesGcm(
    //   encrypted: rust_api.EncryptedData(
    //     ciphertext: encrypted.ciphertext.toList(),
    //     nonce: encrypted.nonce.toList(),
    //     tag: encrypted.tag.toList(),
    //   ),
    //   key: key.toList(),
    //   associatedData: associatedData?.toList(),
    // );
    // return Uint8List.fromList(plaintext);

    throw UnimplementedError(
      'Waiting for flutter_rust_bridge bindings generation',
    );
  }

  @override
  Future<EncryptedData> encryptChaCha20Poly1305({
    required Uint8List plaintext,
    required Uint8List key,
    Uint8List? nonce,
    Uint8List? associatedData,
  }) async {
    _ensureNativeAvailable();

    // TODO: Uncomment when flutter_rust_bridge bindings are generated
    // final encrypted = await rust_api.cryptoEncryptChacha20(
    //   plaintext: plaintext.toList(),
    //   key: key.toList(),
    //   nonce: nonce?.toList(),
    //   associatedData: associatedData?.toList(),
    // );
    // return EncryptedData(
    //   ciphertext: Uint8List.fromList(encrypted.ciphertext),
    //   nonce: Uint8List.fromList(encrypted.nonce),
    //   tag: Uint8List.fromList(encrypted.tag),
    // );

    throw UnimplementedError(
      'Waiting for flutter_rust_bridge bindings generation',
    );
  }

  @override
  Future<Uint8List> decryptChaCha20Poly1305({
    required EncryptedData encrypted,
    required Uint8List key,
    Uint8List? associatedData,
  }) async {
    _ensureNativeAvailable();

    // TODO: Uncomment when flutter_rust_bridge bindings are generated
    // final plaintext = await rust_api.cryptoDecryptChacha20(
    //   encrypted: rust_api.EncryptedData(
    //     ciphertext: encrypted.ciphertext.toList(),
    //     nonce: encrypted.nonce.toList(),
    //     tag: encrypted.tag.toList(),
    //   ),
    //   key: key.toList(),
    //   associatedData: associatedData?.toList(),
    // );
    // return Uint8List.fromList(plaintext);

    throw UnimplementedError(
      'Waiting for flutter_rust_bridge bindings generation',
    );
  }

  // ===== PADMÉ Padding =====

  @override
  Future<Uint8List> padMessage(Uint8List message) async {
    if (!_config.enablePadme) {
      return message;
    }

    _ensureNativeAvailable();

    // TODO: Uncomment when flutter_rust_bridge bindings are generated
    // final padded = await rust_api.cryptoPadMessage(message.toList());
    // return Uint8List.fromList(padded);

    throw UnimplementedError(
      'Waiting for flutter_rust_bridge bindings generation',
    );
  }

  @override
  Future<Uint8List> unpadMessage(Uint8List paddedMessage) async {
    if (!_config.enablePadme) {
      return paddedMessage;
    }

    _ensureNativeAvailable();

    // TODO: Uncomment when flutter_rust_bridge bindings are generated
    // final unpadded = await rust_api.cryptoUnpadMessage(paddedMessage.toList());
    // return Uint8List.fromList(unpadded);

    throw UnimplementedError(
      'Waiting for flutter_rust_bridge bindings generation',
    );
  }

  // ===== Key Derivation =====

  @override
  Future<Uint8List> hkdfDerive({
    required Uint8List inputKeyMaterial,
    required Uint8List info,
    Uint8List? salt,
    int outputLength = 32,
  }) async {
    _ensureNativeAvailable();

    // TODO: Uncomment when flutter_rust_bridge bindings are generated
    // final derived = await rust_api.cryptoHkdf(
    //   inputKeyMaterial: inputKeyMaterial.toList(),
    //   salt: salt?.toList(),
    //   info: info.toList(),
    //   outputLength: outputLength,
    // );
    // return Uint8List.fromList(derived);

    throw UnimplementedError(
      'Waiting for flutter_rust_bridge bindings generation',
    );
  }

  // ===== Signatures =====

  @override
  Future<Uint8List> signEd25519({
    required Uint8List privateKey,
    required Uint8List message,
  }) async {
    _ensureNativeAvailable();

    // TODO: Uncomment when flutter_rust_bridge bindings are generated
    // final signature = rust_api.cryptoSignEd25519(
    //   privateKey: privateKey.toList(),
    //   message: message.toList(),
    // );
    // return Uint8List.fromList(signature);

    throw UnimplementedError(
      'Waiting for flutter_rust_bridge bindings generation',
    );
  }

  @override
  Future<bool> verifyEd25519({
    required Uint8List publicKey,
    required Uint8List message,
    required Uint8List signature,
  }) async {
    _ensureNativeAvailable();

    // TODO: Uncomment when flutter_rust_bridge bindings are generated
    // return rust_api.cryptoVerifyEd25519(
    //   publicKey: publicKey.toList(),
    //   message: message.toList(),
    //   signature: signature.toList(),
    // );

    throw UnimplementedError(
      'Waiting for flutter_rust_bridge bindings generation',
    );
  }
}

/// Extended CryptoBridgeFactory that includes native support
class ExtendedCryptoBridgeFactory {
  static CryptoBridge? _instance;

  /// Get the singleton crypto bridge instance
  static CryptoBridge get instance {
    _instance ??= _createBridge();
    return _instance!;
  }

  static CryptoBridge _createBridge() {
    if (kIsWeb) {
      debugPrint('🔐 Web platform detected, using Dart crypto');
      return DartCryptoBridge();
    }

    // Try native first on mobile/desktop
    if (NativeRustCryptoBridge.checkNativeAvailable()) {
      debugPrint('🔐 Native Rust crypto available');
      return NativeRustCryptoBridge();
    }

    debugPrint('🔐 Native crypto not available, falling back to Dart');
    return DartCryptoBridge();
  }

  /// Reset instance (for testing)
  @visibleForTesting
  static void reset() {
    _instance = null;
  }
}
